## 00-1. Preprocessing (CPTAC-LUAD)

In [1]:
library(data.table)
library(vespa)

In [6]:
out <- system2(
  "bash",
  "./tools/scripts/cptac-luad.sh",
  stdout = TRUE,
  stderr = TRUE
)

cat(out, sep = "\n")

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 90.7M    0 90.7M    0     0  1287k      0 --:--:--  0:01:12 --:--:--  794k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 71.9M    0 71.9M    0     0   830k      0 --:--:--  0:01:28 --:--:--  899k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1971k    0 1971k    0     0  1560k      0 --:--:--  0:00:01 --:--:-- 1561k

In [3]:
out <- system2(
  "bash",
  "./tools/scripts/fasta.sh",
  stdout = TRUE,
  stderr = TRUE
)

cat(out, sep = "\n")

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 27.9M    0 27.9M    0     0   705k      0 --:--:--  0:00:40 --:--:--  547k

## Import data

In [2]:
phospho <- importPhosphoCPTAC(
    "./data/cptac-luad/CPTAC3_Lung_Adeno_Carcinoma_Phosphoproteome.phosphopeptide.tmt10.tsv",
    fasta="./tools/references/library.fasta",
    cores=6
)
phospho

Loading FASTA DB

Loading CPTAC data

Mapping CPTAC peptides to FASTA

Mapping phosphopeptide sites

        gene_id protein_id peptide_id site_id
1       SAMD1   Q6SPF0     PEP_6      SAMD1:Q6SPF0:S161
2       SAMD1   Q6SPF0     PEP_6      SAMD1:Q6SPF0:S161
3       SAMD1   Q6SPF0     PEP_6      SAMD1:Q6SPF0:S161
4       SAMD1   Q6SPF0     PEP_6      SAMD1:Q6SPF0:S161
5       SAMD1   Q6SPF0     PEP_6      SAMD1:Q6SPF0:S161
6       SAMD1   Q6SPF0     PEP_6      SAMD1:Q6SPF0:S161
7       SAMD1   Q6SPF0     PEP_6      SAMD1:Q6SPF0:S161
8       SAMD1   Q6SPF0     PEP_6      SAMD1:Q6SPF0:S161
9       SAMD1   Q6SPF0     PEP_6      SAMD1:Q6SPF0:S161
10      SAMD1   Q6SPF0     PEP_6      SAMD1:Q6SPF0:S161
11      SAMD1   Q6SPF0     PEP_6      SAMD1:Q6SPF0:S161
12      SAMD1   Q6SPF0     PEP_6      SAMD1:Q6SPF0:S161
13      SAMD1   Q6SPF0     PEP_6      SAMD1:Q6SPF0:S161
14      SAMD1   Q6SPF0     PEP_6      SAMD1:Q6SPF0:S161
15      SAMD1   Q6SPF0     PEP_6      SAMD1:Q6SPF0:S161
16      SAMD1   Q6SPF0     PEP_6      SAMD1:Q6SPF0:S161
17      SAMD1   Q6SPF0     PEP_6      SAMD1:Q6SPF0:S161
18      SAMD1   Q6SPF0     PEP_6      SAMD1:Q6SPF0:S161
19      SAMD1   Q6SPF0     PEP_6      SAMD1:Q6SPF0:S161
20      SAMD1   Q6SPF0     PEP_6      SAMD1:Q6SPF0:S161
21      SAMD1   Q6SPF0     PEP_6      SAMD1:Q6SPF0:S161
22      SAMD1   Q6SPF0     PEP_6      SAMD1:Q6SPF0:S161
23      SAMD1   Q6SPF0     PEP_6      SAMD1:Q6SPF0:S161
24      SAMD1   Q6SPF0     PEP_6      SAMD1:Q6SPF0:S161
25      SAMD1   Q6SPF0     PEP_6      SAMD1:Q6SPF0:S161
26      SAMD1   Q6SPF0     PEP_6      SAMD1:Q6SPF0:S161
27      SAMD1   Q6SPF0     PEP_6      SAMD1:Q6SPF0:S161
28      SAMD1   Q6SPF0     PEP_6      SAMD1:Q6SPF0:S161
29      SAMD1   Q6SPF0     PEP_6      SAMD1:Q6SPF0:S161
30      SAMD1   Q6SPF0     PEP_6      SAMD1:Q6SPF0:S161
⋮       ⋮       ⋮          ⋮          ⋮
1202476 TCF25   Q9BQ70     PEP_52425  TCF25:Q9BQ70:S230
1202477 TCF25   Q9BQ70     PEP_52425  TCF25:Q9BQ70:S235
1202478 TCF25   Q9BQ70     PEP_52425  TCF25:Q9BQ70:Y229
1202479 TCF25   Q9BQ70     PEP_52425  TCF25:Q9BQ70:S230
1202480 TCF25   Q9BQ70     PEP_52425  TCF25:Q9BQ70:S235
1202481 TCF25   Q9BQ70     PEP_52425  TCF25:Q9BQ70:Y229
1202482 TCF25   Q9BQ70     PEP_52425  TCF25:Q9BQ70:S230
1202483 TCF25   Q9BQ70     PEP_52425  TCF25:Q9BQ70:S235
1202484 TCF25   Q9BQ70     PEP_52425  TCF25:Q9BQ70:Y229
1202485 TCF25   Q9BQ70     PEP_52425  TCF25:Q9BQ70:S230
1202486 TCF25   Q9BQ70     PEP_52425  TCF25:Q9BQ70:S235
1202487 TCF25   Q9BQ70     PEP_52425  TCF25:Q9BQ70:Y229
1202488 MRC2    Q9UBG0     PEP_52428  MRC2:Q9UBG0:S1453
1202489 MRC2    Q9UBG0     PEP_52428  MRC2:Q9UBG0:Y1452
1202490 MRC2    Q9UBG0     PEP_52428  MRC2:Q9UBG0:S1453
1202491 MRC2    Q9UBG0     PEP_52428  MRC2:Q9UBG0:Y1452
1202492 MRC2    Q9UBG0     PEP_52428  MRC2:Q9UBG0:S1453
1202493 MRC2    Q9UBG0     PEP_52428  MRC2:Q9UBG0:Y1452
1202494 MRC2    Q9UBG0     PEP_52428  MRC2:Q9UBG0:S1453
1202495 MRC2    Q9UBG0     PEP_52428  MRC2:Q9UBG0:Y1452
1202496 MRC2    Q9UBG0     PEP_52428  MRC2:Q9UBG0:S1453
1202497 MRC2    Q9UBG0     PEP_52428  MRC2:Q9UBG0:Y1452
1202498 MRC2    Q9UBG0     PEP_52428  MRC2:Q9UBG0:S1453
1202499 MRC2    Q9UBG0     PEP_52428  MRC2:Q9UBG0:Y1452
1202500 MRC2    Q9UBG0     PEP_52428  MRC2:Q9UBG0:S1453
1202501 MRC2    Q9UBG0     PEP_52428  MRC2:Q9UBG0:Y1452
1202502 MRC2    Q9UBG0     PEP_52428  MRC2:Q9UBG0:S1453
1202503 MRC2    Q9UBG0     PEP_52428  MRC2:Q9UBG0:Y1452
1202504 MRC2    Q9UBG0     PEP_52428  MRC2:Q9UBG0:S1453
1202505 MRC2    Q9UBG0     PEP_52428  MRC2:Q9UBG0:Y1452
        modified_peptide_sequence peptide_sequence     phosphosite
1       AAAAAATAPPsPGPAQPGPR      AAAAAATAPPSPGPAQPGPR S161
2       AAAAAATAPPsPGPAQPGPR      AAAAAATAPPSPGPAQPGPR S161
3       AAAAAATAPPsPGPAQPGPR      AAAAAATAPPSPGPAQPGPR S161
4       AAAAAATAPPsPGPAQPGPR      AAAAAATAPPSPGPAQPGPR S161
5       AAAAAATAPPsPGPAQPGPR      AAAAAATAPPSPGPAQPGPR S161
6       AAAAAATAPPsPGPAQPGPR      AAAAAATAPPSPGPAQPGPR S161
7       AAAAAATAPPsPGPAQPGPR      AAAAAATAPPSPGPAQPGPR S161
8       AAAAAATAPPsPGPAQPGPR      AAAAAATAPPSPGPAQPGPR S161
9       AAAAAATAPPsPGPAQPGPR      AAAAAATAPPSPGPAQPGPR S161
10      AAAAAATAPPsPGPAQPGPR      AAAAAATAPPSPGPAQPGPR S161
11      AAAAAATAPPsPGPAQPGPR      AAAAAATAPPSPGPAQPGPR S161
12      AAAAAATAPPsPGPAQPGPR      AAAAAATAPPSPGPAQPGPR S161
13      AAAAAATAPPsPGPAQPGPR      AAAAAATAPPSPGPAQPGPR S161
14      AAAAAATAPPsPGPAQPGPR      AAAAAATAPPSPGPAQPGPR S161
15      AAAAAATAPPsPGPAQPGPR      AAAAAATAPPSPGPAQPGPR S161
16      AAAAAATAPPsPGPAQPGPR      AAAAAATAPPSPGPAQPGPR S161
17      AAAAAATAPPsPGPAQPGPR      AAAAAATAPPSPGPAQPGPR S161
18      AAAAAATAPPsPGPAQPGPR      AAAAAATAPPSPGPAQPGPR S161
19      AAAAAATAPPsPGPAQPGPR      AAAAAATAPPSPGPAQPGPR S161
20      AAAAAATAPPsPGPAQPGPR      AAAAAATAPPSPGPAQPGPR S161
21      AAAAAATAPPsPGPAQPGPR      AAAAAATAPPSPGPAQPGPR S161
22      AAAAAATAPPsPGPAQPGPR      AAAAAATAPPSPGPAQPGPR S161
23      AAAAAATAPPsPGPAQPGPR      AAAAAATAPPSPGPAQPGPR S161
24      AAAAAATAPPsPGPAQPGPR      AAAAAATAPPSPGPAQPGPR S161
25      AAAAAATAPPsPGPAQPGPR      AAAAAATAPPSPGPAQPGPR S161
26      AAAAAATAPPsPGPAQPGPR      AAAAAATAPPSPGPAQPGPR S161
27      AAAAAATAPPsPGPAQPGPR      AAAAAATAPPSPGPAQPGPR S161
28      AAAAAATAPPsPGPAQPGPR      AAAAAATAPPSPGPAQPGPR S161
29      AAAAAATAPPsPGPAQPGPR      AAAAAATAPPSPGPAQPGPR S161
30      AAAAAATAPPsPGPAQPGPR      AAAAAATAPPSPGPAQPGPR S161
⋮       ⋮                         ⋮                    ⋮
1202476 ysKPGLsMR                 YSKPGLSMR            S230
1202477 ysKPGLsMR                 YSKPGLSMR            S235
1202478 ysKPGLsMR                 YSKPGLSMR            Y229
1202479 ysKPGLsMR                 YSKPGLSMR            S230
1202480 ysKPGLsMR                 YSKPGLSMR            S235
1202481 ysKPGLsMR                 YSKPGLSMR            Y229
1202482 ysKPGLsMR                 YSKPGLSMR            S230
1202483 ysKPGLsMR                 YSKPGLSMR            S235
1202484 ysKPGLsMR                 YSKPGLSMR            Y229
1202485 ysKPGLsMR                 YSKPGLSMR            S230
1202486 ysKPGLsMR                 YSKPGLSMR            S235
1202487 ysKPGLsMR                 YSKPGLSMR            Y229
1202488 ysRSSSSPTEATEK            YSRSSSSPTEATEK       S1453
1202489 ysRSSSSPTEATEK            YSRSSSSPTEATEK       Y1452
1202490 ysRSSSSPTEATEK            YSRSSSSPTEATEK       S1453
1202491 ysRSSSSPTEATEK            YSRSSSSPTEATEK       Y1452
1202492 ysRSSSSPTEATEK            YSRSSSSPTEATEK       S1453
1202493 ysRSSSSPTEATEK            YSRSSSSPTEATEK       Y1452
1202494 ysRSSSSPTEATEK            YSRSSSSPTEATEK       S1453
1202495 ysRSSSSPTEATEK            YSRSSSSPTEATEK       Y1452
1202496 ysRSSSSPTEATEK            YSRSSSSPTEATEK       S1453
1202497 ysRSSSSPTEATEK            YSRSSSSPTEATEK       Y1452
1202498 ysRSSSSPTEATEK            YSRSSSSPTEATEK       S1453
1202499 ysRSSSSPTEATEK            YSRSSSSPTEATEK       Y1452
1202500 ysRSSSSPTEATEK            YSRSSSSPTEATEK       S1453
1202501 ysRSSSSPTEATEK            YSRSSSSPTEATEK       Y1452
1202502 ysRSSSSPTEATEK            YSRSSSSPTEATEK       S1453
1202503 ysRSSSSPTEATEK            YSRSSSSPTEATEK       Y1452
1202504 ysRSSSSPTEATEK            YSRSSSSPTEATEK       S1453
1202505 ysRSSSSPTEATEK            YSRSSSSPTEATEK       Y1452
        run_id          peptide_intensity
1       CPT0089340003    0.334385822
2       CPT0089360003   -0.624646268
3       CPT0092930003    0.103868889
4       CPT0092940003   -0.549610281
5       CPT0015410003    0.009203743
6       CPT0015420003   -0.103037442
7       CPT0146980004    0.221928523
8       CPT0147000003   -0.619828029
9       TumorOnlyIR.1    0.425916227
10      CPT0148280004    0.702575263
11      CPT0148300003   -0.757556671
12      CPT0011710004    0.280163675
13      CPT0011750003   -1.226527322
14      CPT0117970003    0.013346008
15      CPT0118010003   -1.643815471
16      CPT0069360003    0.867419226
17      CPT0069370003   -0.252324681
18      NormalOnlyIR.1  -0.557761647
19      CPT0148080004.1  0.338451131
20      CPT0148100003   -0.586839432
21      CPT0083100003    0.222852551
22      CPT0083140003   -0.710183365
23      CPT0118160003    0.622157783
24      CPT0118180003   -0.939203600
25      CPT0105510003    0.665687479
26      CPT0105550003   -0.003640856
27      TumorOnlyIR.2    0.493783684
28      CPT0091240003    0.508854123
29      CPT0091260003   -0.486518927
30      CPT0148180004    1.061688143
⋮       ⋮               ⋮
1202476 CPT0111590003   -0.02864723
1202477 CPT0111590003   -0.02864723
1202478 CPT0111590003   -0.02864723
1202479 CPT0008410003    0.19822911
1202480 CPT0008410003    0.19822911
1202481 CPT0008410003    0.19822911
1202482 CPT0008420003   -1.42592727
1202483 CPT0008420003   -1.42592727
1202484 CPT0008420003   -1.42592727
1202485 CPT0146700003   -0.31140270
1202486 CPT0146700003   -0.31140270
1202487 CPT0146700003   -0.31140270
1202488 CPT0148080004.1  0.49851594
1202489 CPT0148080004.1  0.49851594
1202490 CPT0148100003   -0.49117404
1202491 CPT0148100003   -0.49117404
1202492 CPT0083100003    0.49654626
1202493 CPT0083100003    0.49654626
1202494 CPT0083140003   -0.26688943
1202495 CPT0083140003   -0.26688943
1202496 CPT0118160003    1.04963344
1202497 CPT0118160003    1.04963344
1202498 CPT0118180003   -1.54306163
1202499 CPT0118180003   -1.54306163
1202500 CPT0105510003    1.05259038
1202501 CPT0105510003    1.05259038
1202502 CPT0105550003   -0.09836768
1202503 CPT0105550003   -0.09836768
1202504 TumorOnlyIR.2    0.35818374
1202505 TumorOnlyIR.2    0.35818374

In [3]:
proteo <- importProteoCPTAC(
    "./data/cptac-luad/CPTAC3_Lung_Adeno_Carcinoma_Proteome.tmt10.tsv",
    fasta="./tools/references/library.fasta"
)
proteo

Loading FASTA DB

Loading CPTAC data

        gene_id  protein_id peptide_id site_id
1       A1BG     P04217     P04217     A1BG:P04217:PA
2       A1CF     Q9NQ94     Q9NQ94     A1CF:Q9NQ94:PA
3       A2M      P01023     P01023     A2M:P01023:PA
4       AAAS     Q9NRG9     Q9NRG9     AAAS:Q9NRG9:PA
5       AACS     Q86V21     Q86V21     AACS:Q86V21:PA
6       AADAC    P22760     P22760     AADAC:P22760:PA
7       AADAT    Q8N5Z0     Q8N5Z0     AADAT:Q8N5Z0:PA
8       AAGAB    Q6PD74     Q6PD74     AAGAB:Q6PD74:PA
9       AAK1     Q2M2I8     Q2M2I8     AAK1:Q2M2I8:PA
10      AAMDC    Q9H7C9     Q9H7C9     AAMDC:Q9H7C9:PA
11      AAMP     Q13685     Q13685     AAMP:Q13685:PA
12      AAR2     Q9Y312     Q9Y312     AAR2:Q9Y312:PA
13      AARS2    Q5JTZ9     Q5JTZ9     AARS2:Q5JTZ9:PA
14      AARSD1   Q9BTE6     Q9BTE6     AARSD1:Q9BTE6:PA
15      AASDHPPT Q9NRN7     Q9NRN7     AASDHPPT:Q9NRN7:PA
16      AASS     Q9UDR5     Q9UDR5     AASS:Q9UDR5:PA
17      AATF     Q9NY61     Q9NY61     AATF:Q9NY61:PA
18      AATK     Q6ZMQ8     Q6ZMQ8     AATK:Q6ZMQ8:PA
19      ABAT     P80404     P80404     ABAT:P80404:PA
20      ABCA1    O95477     O95477     ABCA1:O95477:PA
21      ABCA12   Q86UK0     Q86UK0     ABCA12:Q86UK0:PA
22      ABCA2    Q9BZC7     Q9BZC7     ABCA2:Q9BZC7:PA
23      ABCA3    Q99758     Q99758     ABCA3:Q99758:PA
24      ABCA6    Q8N139     Q8N139     ABCA6:Q8N139:PA
25      ABCA7    Q8IZY2     Q8IZY2     ABCA7:Q8IZY2:PA
26      ABCA8    O94911     O94911     ABCA8:O94911:PA
27      ABCB1    P08183     P08183     ABCB1:P08183:PA
28      ABCB10   Q9NRK6     Q9NRK6     ABCB10:Q9NRK6:PA
29      ABCB6    Q9NP58     Q9NP58     ABCB6:Q9NP58:PA
30      ABCB7    O75027     O75027     ABCB7:O75027:PA
⋮       ⋮        ⋮          ⋮          ⋮
2409721 ZNF830   Q96NB3     Q96NB3     ZNF830:Q96NB3:PA
2409722 ZNF845   Q96IR2     Q96IR2     ZNF845:Q96IR2:PA
2409723 ZNF852   Q6ZMS4     Q6ZMS4     ZNF852:Q6ZMS4:PA
2409724 ZNF865   P0CJ78     P0CJ78     ZNF865:P0CJ78:PA
2409725 ZNF91    Q05481     Q05481     ZNF91:Q05481:PA
2409726 ZNFX1    Q9P2E3     Q9P2E3     ZNFX1:Q9P2E3:PA
2409727 ZNHIT1   O43257     O43257     ZNHIT1:O43257:PA
2409728 ZNHIT2   Q9UHR6     Q9UHR6     ZNHIT2:Q9UHR6:PA
2409729 ZNHIT3   Q15649     Q15649     ZNHIT3:Q15649:PA
2409730 ZNHIT6   Q9NWK9     Q9NWK9     ZNHIT6:Q9NWK9:PA
2409731 ZNRF1    Q8ND25     Q8ND25     ZNRF1:Q8ND25:PA
2409732 ZNRF2    Q8NHG8     Q8NHG8     ZNRF2:Q8NHG8:PA
2409733 ZPR1     O75312     O75312     ZPR1:O75312:PA
2409734 ZRANB2   O95218     O95218     ZRANB2:O95218:PA
2409735 ZRSR2    Q15696     Q15696     ZRSR2:Q15696:PA
2409736 ZSCAN18  Q8TBC5     Q8TBC5     ZSCAN18:Q8TBC5:PA
2409737 ZSCAN26  Q16670     Q16670     ZSCAN26:Q16670:PA
2409738 ZSCAN31  Q96LW9     Q96LW9     ZSCAN31:Q96LW9:PA
2409739 ZSWIM4   Q9H7M6     Q9H7M6     ZSWIM4:Q9H7M6:PA
2409740 ZSWIM8   A7E2V4     A7E2V4     ZSWIM8:A7E2V4:PA
2409741 ZSWIM9   Q86XI8     Q86XI8     ZSWIM9:Q86XI8:PA
2409742 ZW10     O43264     O43264     ZW10:O43264:PA
2409743 ZWILCH   Q9H900     Q9H900     ZWILCH:Q9H900:PA
2409744 ZWINT    O95229     O95229     ZWINT:O95229:PA
2409745 ZXDA     P98168     P98168     ZXDA:P98168:PA
2409746 ZXDC     Q2QGD7     Q2QGD7     ZXDC:Q2QGD7:PA
2409747 ZYG11B   Q9C0D3     Q9C0D3     ZYG11B:Q9C0D3:PA
2409748 ZYX      Q15942     Q15942     ZYX:Q15942:PA
2409749 ZZEF1    O43149     O43149     ZZEF1:O43149:PA
2409750 ZZZ3     Q8IYH5     Q8IYH5     ZZZ3:Q8IYH5:PA
        modified_peptide_sequence peptide_sequence phosphosite run_id
1       P04217                    P04217           PA          CPT0089340003
2       Q9NQ94                    Q9NQ94           PA          CPT0089340003
3       P01023                    P01023           PA          CPT0089340003
4       Q9NRG9                    Q9NRG9           PA          CPT0089340003
5       Q86V21                    Q86V21           PA          CPT0089340003
6       P22760                    P22760           PA          CPT0089340003
7       Q8N5Z0                    Q8N5Z0           PA          CPT0089340003
8       Q6PD74                    Q6PD74           PA          CPT0089340003
9       Q2M2I8                    Q2M2I8           PA          CPT0089340003
10      Q9H7C9                    Q9H7C9           PA          CPT0089340003
11      Q13685                    Q13685           PA          CPT0089340003
12      Q9Y312                    Q9Y312           PA          CPT0089340003
13      Q5JTZ9                    Q5JTZ9           PA          CPT0089340003
14      Q9BTE6                    Q9BTE6           PA          CPT0089340003
15      Q9NRN7                    Q9NRN7           PA          CPT0089340003
16      Q9UDR5                    Q9UDR5           PA          CPT0089340003
17      Q9NY61                    Q9NY61           PA          CPT0089340003
18      Q6ZMQ8                    Q6ZMQ8           PA          CPT0089340003
19      P80404                    P80404           PA          CPT0089340003
20      O95477                    O95477           PA          CPT0089340003
21      Q86UK0                    Q86UK0           PA          CPT0089340003
22      Q9BZC7                    Q9BZC7           PA          CPT0089340003
23      Q99758                    Q99758           PA          CPT0089340003
24      Q8N139                    Q8N139           PA          CPT0089340003
25      Q8IZY2                    Q8IZY2           PA          CPT0089340003
26      O94911                    O94911           PA          CPT0089340003
27      P08183                    P08183           PA          CPT0089340003
28      Q9NRK6                    Q9NRK6           PA          CPT0089340003
29      Q9NP58                    Q9NP58           PA          CPT0089340003
30      O75027                    O75027           PA          CPT0089340003
⋮       ⋮                         ⋮                ⋮           ⋮
2409721 Q96NB3                    Q96NB3           PA          NormalOnlyIR.4
2409722 Q96IR2                    Q96IR2           PA          NormalOnlyIR.4
2409723 Q6ZMS4                    Q6ZMS4           PA          NormalOnlyIR.4
2409724 P0CJ78                    P0CJ78           PA          NormalOnlyIR.4
2409725 Q05481                    Q05481           PA          NormalOnlyIR.4
2409726 Q9P2E3                    Q9P2E3           PA          NormalOnlyIR.4
2409727 O43257                    O43257           PA          NormalOnlyIR.4
2409728 Q9UHR6                    Q9UHR6           PA          NormalOnlyIR.4
2409729 Q15649                    Q15649           PA          NormalOnlyIR.4
2409730 Q9NWK9                    Q9NWK9           PA          NormalOnlyIR.4
2409731 Q8ND25                    Q8ND25           PA          NormalOnlyIR.4
2409732 Q8NHG8                    Q8NHG8           PA          NormalOnlyIR.4
2409733 O75312                    O75312           PA          NormalOnlyIR.4
2409734 O95218                    O95218           PA          NormalOnlyIR.4
2409735 Q15696                    Q15696           PA          NormalOnlyIR.4
2409736 Q8TBC5                    Q8TBC5           PA          NormalOnlyIR.4
2409737 Q16670                    Q16670           PA          NormalOnlyIR.4
2409738 Q96LW9                    Q96LW9           PA          NormalOnlyIR.4
2409739 Q9H7M6                    Q9H7M6           PA          NormalOnlyIR.4
2409740 A7E2V4                    A7E2V4           PA          NormalOnlyIR.4
2409741 Q86XI8                    Q86XI8           PA          NormalOnlyIR.4
2409742 O43264                    O43264           PA          NormalOnlyIR.4
2409743 Q9H900                    Q9H900           PA          NormalOnlyIR.4
2409744 O95229                    O95229           PA          NormalOnlyIR.4
2409745 P98168                    P98168           PA          NormalOnlyIR.4
2409746 Q2QGD7                    Q2QGD7           PA          NormalOnlyIR.4
2409747 Q9C0D3                    Q9C0D3           PA          NormalOnlyIR.4
2409748 Q15942                    Q15942           PA          NormalOnlyIR.4
2409749 O43149                    O43149           PA          NormalOnlyIR.4
2409750 Q8IYH5                    Q8IYH5           PA          NormalOnlyIR.4
        peptide_intensity
1       -0.608178218
2                 NA
3       -0.852777619
4        0.063600148
5       -0.124289958
6       -2.281265494
7       -0.869112802
8       -0.091862293
9       -0.002046645
10       0.175400585
11       0.339276762
12       0.021640839
13      -0.150221550
14       0.358136801
15       0.386885484
16       0.209195785
17       0.775807351
18      -0.438669789
19       0.500467253
20      -0.444890962
21                NA
22       0.467599205
23      -1.556549386
24      -0.233133122
25       0.095722294
26      -0.698130760
27      -0.182074489
28       0.843830594
29       0.098256078
30       0.514599604
⋮       ⋮
2409721 -0.10253049
2409722 -0.20109283
2409723  0.15132910
2409724  0.20000349
2409725  0.53714645
2409726 -0.13439134
2409727 -0.25802305
2409728 -0.25889564
2409729 -0.64448856
2409730  0.02370994
2409731          NA
2409732 -0.39425773
2409733 -0.36553236
2409734 -0.25503582
2409735 -0.76627947
2409736  0.01324926
2409737  0.02676684
2409738 -0.33076450
2409739          NA
2409740  0.01046398
2409741  0.18753392
2409742 -0.13183501
2409743 -1.03084618
2409744          NA
2409745          NA
2409746  0.86513129
2409747  0.07386401
2409748  0.40129448
2409749  0.13473647
2409750  0.17996214

In [4]:
clin <- fread("./data/cptac-luad/S046_Lung_Adenocarcinoma.csv")
clin

      Dataset    Run                                               Cohort
1     CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f01.mzML          Lung Cancer
2     CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f01.mzML          Normal
3     CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f01.mzML          Lung Cancer
4     CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f01.mzML          Normal
5     CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f01.mzML          Lung Cancer
6     CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f01.mzML          Normal
7     CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f01.mzML          Lung Cancer
8     CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f01.mzML          Normal
9     CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f01.mzML          Tumor Norm
10    CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f01.mzML          Norm
11    CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f02_reinject.mzML Lung Cancer
12    CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f02_reinject.mzML Normal
13    CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f02_reinject.mzML Lung Cancer
14    CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f02_reinject.mzML Normal
15    CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f02_reinject.mzML Lung Cancer
16    CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f02_reinject.mzML Normal
17    CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f02_reinject.mzML Lung Cancer
18    CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f02_reinject.mzML Normal
19    CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f02_reinject.mzML Tumor Norm
20    CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f02_reinject.mzML Norm
21    CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f03.mzML          Lung Cancer
22    CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f03.mzML          Normal
23    CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f03.mzML          Lung Cancer
24    CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f03.mzML          Normal
25    CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f03.mzML          Lung Cancer
26    CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f03.mzML          Normal
27    CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f03.mzML          Lung Cancer
28    CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f03.mzML          Normal
29    CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f03.mzML          Tumor Norm
30    CPTAC_S046 01CPTAC_LUAD_AcK_BI_20180517_BD_f03.mzML          Norm
⋮     ⋮          ⋮                                                 ⋮
12151 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f23.mzML            Lung Cancer
12152 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f23.mzML            Normal
12153 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f23.mzML            Lung Cancer
12154 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f23.mzML            Normal
12155 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f23.mzML            Lung Cancer
12156 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f23.mzML            Normal
12157 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f23.mzML            Lung Cancer
12158 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f23.mzML            Normal
12159 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f23.mzML            Normal Norm
12160 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f23.mzML            Norm
12161 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f24.mzML            Lung Cancer
12162 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f24.mzML            Normal
12163 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f24.mzML            Lung Cancer
12164 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f24.mzML            Normal
12165 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f24.mzML            Lung Cancer
12166 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f24.mzML            Normal
12167 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f24.mzML            Lung Cancer
12168 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f24.mzML            Normal
12169 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f24.mzML            Normal Norm
12170 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f24.mzML            Norm
12171 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f25.mzML            Lung Cancer
12172 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f25.mzML            Normal
12173 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f25.mzML            Lung Cancer
12174 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f25.mzML            Normal
12175 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f25.mzML            Lung Cancer
12176 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f25.mzML            Normal
12177 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f25.mzML            Lung Cancer
12178 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f25.mzML            Normal
12179 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f25.mzML            Normal Norm
12180 CPTAC_S046 25CPTAC_LUAD_W_BI_20180901_KR_f25.mzML            Norm
      Subject           Condition   TimePoint BioReplicate Experiment Mixture
1     Patient_C3N-01799 Lung Cancer NA        1            1          1
2     Patient_C3N-01799 Normal      NA        1            1          1
3     Patient_C3L-01890 Lung Cancer NA        2            2          1
4     Patient_C3L-01890 Normal      NA        2            2          1
5     Patient_C3N-00572 Lung Cancer NA        3            3          1
6     Patient_C3N-00572 Normal      NA        3            3          1
7     Patient_C3N-02423 Lung Cancer NA        4            4          1
8     Patient_C3N-02423 Normal      NA        4            4          1
9     Tumor Norm        Tumor Norm  NA        1            1          1
10    Norm              Norm        NA        Norm         Norm       1
11    Patient_C3N-01799 Lung Cancer NA        1            1          1
12    Patient_C3N-01799 Normal      NA        1            1          1
13    Patient_C3L-01890 Lung Cancer NA        2            2          1
14    Patient_C3L-01890 Normal      NA        2            2          1
15    Patient_C3N-00572 Lung Cancer NA        3            3          1
16    Patient_C3N-00572 Normal      NA        3            3          1
17    Patient_C3N-02423 Lung Cancer NA        4            4          1
18    Patient_C3N-02423 Normal      NA        4            4          1
19    Tumor Norm        Tumor Norm  NA        1            1          1
20    Norm              Norm        NA        Norm         Norm       1
21    Patient_C3N-01799 Lung Cancer NA        1            1          1
22    Patient_C3N-01799 Normal      NA        1            1          1
23    Patient_C3L-01890 Lung Cancer NA        2            2          1
24    Patient_C3L-01890 Normal      NA        2            2          1
25    Patient_C3N-00572 Lung Cancer NA        3            3          1
26    Patient_C3N-00572 Normal      NA        3            3          1
27    Patient_C3N-02423 Lung Cancer NA        4            4          1
28    Patient_C3N-02423 Normal      NA        4            4          1
29    Tumor Norm        Tumor Norm  NA        1            1          1
30    Norm              Norm        NA        Norm         Norm       1
⋮     ⋮                 ⋮           ⋮         ⋮            ⋮          ⋮
12151 Patient_C3N-00175 Lung Cancer NA        110          1          25
12152 Patient_C3N-00175 Normal      NA        99           1          25
12153 Patient_C3N-01823 Lung Cancer NA        111          2          25
12154 Patient_C3N-01823 Normal      NA        100          2          25
12155 Patient_C3L-02549 Lung Cancer NA        112          3          25
12156 Patient_C3L-02549 Normal      NA        101          3          25
12157 Patient_C3L-02365 Lung Cancer NA        113          4          25
12158 Patient_C3L-02365 Normal      NA        102          4          25
12159 Normal Norm       Normal Norm NA        4            1          25
12160 Norm              Norm        NA        Norm         Norm       25
12161 Patient_C3N-00175 Lung Cancer NA        110          1          25
12162 Patient_C3N-00175 Normal      NA        99           1          25
12163 Patient_C3N-01823 Lung Cancer NA        111          2          25
12164 Patient_C3N-01823 Normal      NA        100          2          25
12165 Patient_C3L-02549 Lung Cancer NA        112          3          25
12166 Patient_C3L-02549 Normal      NA        101          3          25
12167 Patient_C3L-02365 Lung Cancer NA        113          4          25
12168 Patient_C3L-02365 Normal      NA        102          4          25
12169 Normal Norm       Normal Norm NA        4            1          25
12170 Norm              Norm        NA        Norm         Norm       25
12171 Patient_C3N-00175 Lung Cancer NA        110          1          25
12172 Patient_C3N-00175 Normal      NA        99           1          25
12173 Patient_C3N-01823 Lung Cancer NA        111          2          25
12174 Patient_C3N-01823 Normal      NA        100          2          25
12175 Patient_C3L-02549 Lung Cancer NA        112          3          25
12176 Patient_C3L-02549 Normal      NA        101          3          25
12177 Patient_C3L-02365 Lung Cancer NA        113          4          25
12178 Patient_C3L-02365 Normal      NA        102          4          25
12179 Normal Norm       Normal Norm NA        4            1          25
12180 Norm              Norm        NA        Norm         Norm       25
      TechRepMixture Batch     Channel Fraction Species        Disease
1     1              Acetylome 126     1        NCBITaxon:9606 DOID:1324
2     1              Acetylome 127N    1        NCBITaxon:9606
3     1              Acetylome 127C    1        NCBITaxon:9606 DOID:1324
4     1              Acetylome 128N    1        NCBITaxon:9606
5     1              Acetylome 128C    1        NCBITaxon:9606 DOID:1324
6     1              Acetylome 129N    1        NCBITaxon:9606
7     1              Acetylome 129C    1        NCBITaxon:9606 DOID:1324
8     1              Acetylome 130N    1        NCBITaxon:9606
9     1              Acetylome 130C    1        NCBITaxon:9606 DOID:1324
10    1              Acetylome 131     1        NCBITaxon:9606
11    1              Acetylome 126     2        NCBITaxon:9606 DOID:1324
12    1              Acetylome 127N    2        NCBITaxon:9606
13    1              Acetylome 127C    2        NCBITaxon:9606 DOID:1324
14    1              Acetylome 128N    2        NCBITaxon:9606
15    1              Acetylome 128C    2        NCBITaxon:9606 DOID:1324
16    1              Acetylome 129N    2        NCBITaxon:9606
17    1              Acetylome 129C    2        NCBITaxon:9606 DOID:1324
18    1              Acetylome 130N    2        NCBITaxon:9606
19    1              Acetylome 130C    2        NCBITaxon:9606 DOID:1324
20    1              Acetylome 131     2        NCBITaxon:9606
21    1              Acetylome 126     3        NCBITaxon:9606 DOID:1324
22    1              Acetylome 127N    3        NCBITaxon:9606
23    1              Acetylome 127C    3        NCBITaxon:9606 DOID:1324
24    1              Acetylome 128N    3        NCBITaxon:9606
25    1              Acetylome 128C    3        NCBITaxon:9606 DOID:1324
26    1              Acetylome 129N    3        NCBITaxon:9606
27    1              Acetylome 129C    3        NCBITaxon:9606 DOID:1324
28    1              Acetylome 130N    3        NCBITaxon:9606
29    1              Acetylome 130C    3        NCBITaxon:9606 DOID:1324
30    1              Acetylome 131     3        NCBITaxon:9606
⋮     ⋮              ⋮         ⋮       ⋮        ⋮              ⋮
12151 1              Proteome  126     23       NCBITaxon:9606 DOID:1324
12152 1              Proteome  127N    23       NCBITaxon:9606
12153 1              Proteome  127C    23       NCBITaxon:9606 DOID:1324
12154 1              Proteome  128N    23       NCBITaxon:9606
12155 1              Proteome  128C    23       NCBITaxon:9606 DOID:1324
12156 1              Proteome  129N    23       NCBITaxon:9606
12157 1              Proteome  129C    23       NCBITaxon:9606 DOID:1324
12158 1              Proteome  130N    23       NCBITaxon:9606
12159 1              Proteome  130C    23       NCBITaxon:9606
12160 1              Proteome  131     23       NCBITaxon:9606
12161 1              Proteome  126     24       NCBITaxon:9606 DOID:1324
12162 1              Proteome  127N    24       NCBITaxon:9606
12163 1              Proteome  127C    24       NCBITaxon:9606 DOID:1324
12164 1              Proteome  128N    24       NCBITaxon:9606
12165 1              Proteome  128C    24       NCBITaxon:9606 DOID:1324
12166 1              Proteome  129N    24       NCBITaxon:9606
12167 1              Proteome  129C    24       NCBITaxon:9606 DOID:1324
12168 1              Proteome  130N    24       NCBITaxon:9606
12169 1              Proteome  130C    24       NCBITaxon:9606
12170 1              Proteome  131     24       NCBITaxon:9606
12171 1              Proteome  126     25       NCBITaxon:9606 DOID:1324
12172 1              Proteome  127N    25       NCBITaxon:9606
12173 1              Proteome  127C    25       NCBITaxon:9606 DOID:1324
12174 1              Proteome  128N    25       NCBITaxon:9606
12175 1              Proteome  128C    25       NCBITaxon:9606 DOID:1324
12176 1              Proteome  129N    25       NCBITaxon:9606
12177 1              Proteome  129C    25       NCBITaxon:9606 DOID:1324
12178 1              Proteome  130N    25       NCBITaxon:9606
12179 1              Proteome  130C    25       NCBITaxon:9606
12180 1              Proteome  131     25       NCBITaxon:9606
      Tissue                  Enzyme     Notes
1     BTO:0000551             MS:1001251 NA
2     BTO:0000763             MS:1001251 NA
3     BTO:0000551             MS:1001251 NA
4     BTO:0000763             MS:1001251 NA
5     BTO:0000551             MS:1001251 NA
6     BTO:0000763             MS:1001251 NA
7     BTO:0000551             MS:1001251 NA
8     BTO:0000763             MS:1001251 NA
9     BTO:0000551             MS:1001251 NA
10    BTO:0000763;BTO:0000551 MS:1001251 NA
11    BTO:0000551             MS:1001251 NA
12    BTO:0000763             MS:1001251 NA
13    BTO:0000551             MS:1001251 NA
14    BTO:0000763             MS:1001251 NA
15    BTO:0000551             MS:1001251 NA
16    BTO:0000763             MS:1001251 NA
17    BTO:0000551             MS:1001251 NA
18    BTO:0000763             MS:1001251 NA
19    BTO:0000551             MS:1001251 NA
20    BTO:0000763;BTO:0000551 MS:1001251 NA
21    BTO:0000551             MS:1001251 NA
22    BTO:0000763             MS:1001251 NA
23    BTO:0000551             MS:1001251 NA
24    BTO:0000763             MS:1001251 NA
25    BTO:0000551             MS:1001251 NA
26    BTO:0000763             MS:1001251 NA
27    BTO:0000551             MS:1001251 NA
28    BTO:0000763             MS:1001251 NA
29    BTO:0000551             MS:1001251 NA
30    BTO:0000763;BTO:0000551 MS:1001251 NA
⋮     ⋮                       ⋮          ⋮
12151 BTO:0000551             MS:1001251 NA
12152 BTO:0000763             MS:1001251 NA
12153 BTO:0000551             MS:1001251 NA
12154 BTO:0000763             MS:1001251 NA
12155 BTO:0000551             MS:1001251 NA
12156 BTO:0000763             MS:1001251 NA
12157 BTO:0000551             MS:1001251 NA
12158 BTO:0000763             MS:1001251 NA
12159 BTO:0000763             MS:1001251 NA
12160 BTO:0000763;BTO:0000551 MS:1001251 NA
12161 BTO:0000551             MS:1001251 NA
12162 BTO:0000763             MS:1001251 NA
12163 BTO:0000551             MS:1001251 NA
12164 BTO:0000763             MS:1001251 NA
12165 BTO:0000551             MS:1001251 NA
12166 BTO:0000763             MS:1001251 NA
12167 BTO:0000551             MS:1001251 NA
12168 BTO:0000763             MS:1001251 NA
12169 BTO:0000763             MS:1001251 NA
12170 BTO:0000763;BTO:0000551 MS:1001251 NA
12171 BTO:0000551             MS:1001251 NA
12172 BTO:0000763             MS:1001251 NA
12173 BTO:0000551             MS:1001251 NA
12174 BTO:0000763             MS:1001251 NA
12175 BTO:0000551             MS:1001251 NA
12176 BTO:0000763             MS:1001251 NA
12177 BTO:0000551             MS:1001251 NA
12178 BTO:0000763             MS:1001251 NA
12179 BTO:0000763             MS:1001251 NA
12180 BTO:0000763;BTO:0000551 MS:1001251 NA

## Extract tumor samples

In [5]:
channel_levels <- c(
  "126", "127N", "127C", "128N", "128C",
  "129N", "129C", "130N", "130C", "131"
)

In [6]:
phospho_ann <- unique(
  clin[
    Batch == "Phosphoproteome",
    .(
      Mixture,
      Channel,
      Subject,
      Condition,
      BioReplicate,
      Cohort
    )
  ]
)

phospho_ann[, channel_order := match(Channel, channel_levels)]
setorder(phospho_ann, Mixture, channel_order)

phospho_ann <- phospho_ann[Condition != "Norm"]
phospho_ann[, run_id := unique(phospho$run_id)]
phospho_ann[, subject_id := sub("^Patient_", "", Subject)]
phospho_ann[, subject_id := gsub("-", ".", subject_id)]

In [14]:
phospho_ann <- phospho_ann[Condition == "Lung Cancer"]
phospho <- phospho[run_id %in% phospho_ann$run_id]
uniqueN(phospho$run_id)

[1] 113

In [8]:
proteo_ann <- unique(
  clin[
    Batch == "Proteome",
    .(
      Mixture,
      Channel,
      Subject,
      Condition,
      BioReplicate,
      Cohort
    )
  ]
)

proteo_ann[, channel_order := match(Channel, channel_levels)]
setorder(proteo_ann, Mixture, channel_order)

proteo_ann <- proteo_ann[Condition != "Norm"]
proteo_ann[, run_id := unique(proteo$run_id)]
proteo_ann[, subject_id := sub("^Patient_", "", Subject)]
proteo_ann[, subject_id := gsub("-", ".", subject_id)]

In [15]:
proteo_ann <- proteo_ann[Condition == "Lung Cancer"]
proteo <- proteo[run_id %in% proteo_ann$run_id]
uniqueN(proteo$run_id)

[1] 113

In [16]:
common_subjects <- intersect(
  phospho_ann$subject_id,
  proteo_ann$subject_id
)

length(common_subjects)

[1] 111

## Exclude patients with multiple runs

In [42]:
dup_subjects_phospho <- phospho_ann[
  subject_id %in% common_subjects,
  .N,
  by = subject_id
][
  N > 1,
  subject_id
]

dup_subjects_proteo <- proteo_ann[
  subject_id %in% common_subjects,
  .N,
  by = subject_id
][
  N > 1,
  subject_id
]

dup_subjects <- union(
  dup_subjects_phospho,
  dup_subjects_proteo
)

dup_subjects

[1] "C3N.02587" "C3N.02379"

In [44]:
common_subjects <- setdiff(
  common_subjects,
  dup_subjects
)

length(common_subjects)

[1] 109

In [45]:
phospho <- phospho[
    run_id %in% phospho_ann[
        subject_id %in% common_subjects,
        run_id
        ]
    ]
uniqueN(phospho$run_id)

[1] 109

In [46]:
proteo <- proteo[
    run_id %in% proteo_ann[
        subject_id %in% common_subjects,
        run_id
        ]
    ]
uniqueN(proteo$run_id)

[1] 109

In [47]:
saveRDS(phospho, "./data/cptac-luad/CPTAC_LUAD_phospho.rds")
saveRDS(proteo,  "./data/cptac-luad/CPTAC_LUAD_proteo.rds")