# 00-1. Preprocessing (CPTAC-COAD)

In [1]:
library(data.table)
library(vespa)

In [2]:
if (!dir.exists("./data/cptac-coad")) {
  out <- system2(
    "bash",
    "./tools/scripts/cptac-coad.sh",
    stdout = TRUE,
    stderr = TRUE
  )

  cat(out, sep = "\n")
}

In [3]:
if (!file.exists("./tools/references/library.fasta")) {
  out <- system2(
    "bash",
    "./tools/scripts/fasta.sh",
    stdout = TRUE,
    stderr = TRUE
  )

  cat(out, sep = "\n")
}

## Import data

In [4]:
phospho <- importPhosphoCCT(
    "./data/cptac-coad/Human__CPTAC_COAD__PNNL__Phosphoproteome__TMT__03_01_2017__BCM__Site__Tumor_PNNL_TMT_LogRatio.cct.gz"
)

Loading CCT data

Warning message in fread(file):
“Detected 97 column names but the data has 98 columns (i.e. invalid file). Added an extra default column name for the first column which is guessed to be row names or an index. Use setnames() afterwards if this guess is not correct, or fix the file write command that created the file to create a valid file.”

In [5]:
phospho

        gene_id   protein_id peptide_id
1       UBA6      A0AVT1     UBA6_S36__A0AVT1:S36
2       ESYT2     A0FGR8     ESYT2_S693__A0FGR8:S693
3       ESYT2     A0FGR8     ESYT2_S704__A0FGR8:S704
4       ESYT2     A0FGR8     ESYT2_S739__A0FGR8:S739
5       ESYT2     A0FGR8     ESYT2_S755__A0FGR8:S755
6       ESYT2     A0FGR8     ESYT2_S758__A0FGR8:S758
7       ESYT2     A0FGR8     ESYT2_S761__A0FGR8:S761
8       ESYT2     A0FGR8     ESYT2_T705__A0FGR8:T705
9       MED19     A0JLT2     MED19_S226__A0JLT2:S226
10      UHRF1BP1L A0JNW5     UHRF1BP1L_S1402__A0JNW5:S1402
11      UHRF1BP1L A0JNW5     UHRF1BP1L_S891__A0JNW5:S891
12      UHRF1BP1L A0JNW5     UHRF1BP1L_S939__A0JNW5:S939
13      UHRF1BP1L A0JNW5     UHRF1BP1L_S989__A0JNW5:S989
14      SHTN1     A0MZ66     SHTN1_S494__A0MZ66:S494
15      BICDL2    A1A5D9     BICDL2_S277__A1A5D9:S277
16      BICDL2    A1A5D9     BICDL2_S36__A1A5D9:S36
17      BICDL2    A1A5D9     BICDL2_T348__A1A5D9:T348
18      C1orf226  A1L170     C1orf226_S198__A1L170:S198
19      C1orf226  A1L170     C1orf226_S222__A1L170:S222
20      C1orf226  A1L170     C1orf226_S244__A1L170:S244
21      PLEKHG3   A1L390     PLEKHG3_S1037__A1L390:S1037
22      PLEKHG3   A1L390     PLEKHG3_S1040__A1L390:S1040
23      PLEKHG3   A1L390     PLEKHG3_S1081__A1L390:S1081
24      PLEKHG3   A1L390     PLEKHG3_S1154__A1L390:S1154
25      PLEKHG3   A1L390     PLEKHG3_S1169__A1L390:S1169
26      PLEKHG3   A1L390     PLEKHG3_S433__A1L390:S433
27      PLEKHG3   A1L390     PLEKHG3_S488__A1L390:S488
28      PLEKHG3   A1L390     PLEKHG3_S576__A1L390:S576
29      PLEKHG3   A1L390     PLEKHG3_S577__A1L390:S577
30      PLEKHG3   A1L390     PLEKHG3_S618__A1L390:S618
⋮       ⋮         ⋮          ⋮
1224079 SLC4A4    Q9Y6R1     SLC4A4_S262__Q9Y6R1:S262
1224080 SLC4A4    Q9Y6R1     SLC4A4_S65__Q9Y6R1:S65
1224081 SLC4A4    Q9Y6R1     SLC4A4_S68__Q9Y6R1:S68
1224082 SLC4A4    Q9Y6R1     SLC4A4_S79__Q9Y6R1:S79
1224083 MAP3K4    Q9Y6R4     MAP3K4_S1252__Q9Y6R4:S1252
1224084 MAP3K4    Q9Y6R4     MAP3K4_S431__Q9Y6R4:S431
1224085 MAP3K4    Q9Y6R4     MAP3K4_S499__Q9Y6R4:S499
1224086 MAP3K4    Q9Y6R4     MAP3K4_S66__Q9Y6R4:S66
1224087 MAP3K4    Q9Y6R4     MAP3K4_T83__Q9Y6R4:T83
1224088 CCDC61    Q9Y6R9     CCDC61_S334__Q9Y6R9:S334
1224089 CCDC61    Q9Y6R9     CCDC61_S336__Q9Y6R9:S336
1224090 CCDC61    Q9Y6R9     CCDC61_S373__Q9Y6R9:S373
1224091 CCDC61    Q9Y6R9     CCDC61_S376__Q9Y6R9:S376
1224092 PCLO      Q9Y6V0     PCLO_S772__Q9Y6V0:S772
1224093 WASF2     Q9Y6W5     WASF2_T129__Q9Y6W5:T129
1224094 FAM169A   Q9Y6X4     FAM169A_S376__Q9Y6X4:S376
1224095 FAM169A   Q9Y6X4     FAM169A_S378__Q9Y6X4:S378
1224096 FAM169A   Q9Y6X4     FAM169A_S449__Q9Y6X4:S449
1224097 FAM169A   Q9Y6X4     FAM169A_S526__Q9Y6X4:S526
1224098 ZHX2      Q9Y6X8     ZHX2_T37__Q9Y6X8:T37
1224099 MORC2     Q9Y6X9     MORC2_S615__Q9Y6X9:S615
1224100 MORC2     Q9Y6X9     MORC2_S725__Q9Y6X9:S725
1224101 MORC2     Q9Y6X9     MORC2_S739__Q9Y6X9:S739
1224102 MORC2     Q9Y6X9     MORC2_S743__Q9Y6X9:S743
1224103 MORC2     Q9Y6X9     MORC2_S777__Q9Y6X9:S777
1224104 MORC2     Q9Y6X9     MORC2_S779__Q9Y6X9:S779
1224105 IVNS1ABP  Q9Y6Y0     IVNS1ABP_S277__Q9Y6Y0:S277
1224106 IVNS1ABP  Q9Y6Y0     IVNS1ABP_S322__Q9Y6Y0:S322
1224107 IVNS1ABP  Q9Y6Y0     IVNS1ABP_S326__Q9Y6Y0:S326
1224108 IVNS1ABP  Q9Y6Y0     IVNS1ABP_S338__Q9Y6Y0:S338
        site_id                modified_peptide_sequence
1       UBA6:A0AVT1:S36        UBA6_S36__A0AVT1:S36
2       ESYT2:A0FGR8:S693      ESYT2_S693__A0FGR8:S693
3       ESYT2:A0FGR8:S704      ESYT2_S704__A0FGR8:S704
4       ESYT2:A0FGR8:S739      ESYT2_S739__A0FGR8:S739
5       ESYT2:A0FGR8:S755      ESYT2_S755__A0FGR8:S755
6       ESYT2:A0FGR8:S758      ESYT2_S758__A0FGR8:S758
7       ESYT2:A0FGR8:S761      ESYT2_S761__A0FGR8:S761
8       ESYT2:A0FGR8:T705      ESYT2_T705__A0FGR8:T705
9       MED19:A0JLT2:S226      MED19_S226__A0JLT2:S226
10      UHRF1BP1L:A0JNW5:S1402 UHRF1BP1L_S1402__A0JNW5:S1402
11      UHRF1BP1L:A0JNW5:S891  UHRF1BP1L_S891__A0JNW5:S891
12      UHRF1BP1L:A0JNW5:S939  UHRF1BP1L_S939__A0JNW5:S939
13      UHRF1BP1L:A0JNW5:S989  UHRF1BP1L_S989__A0JNW5:S989
14      SHTN1:A0MZ66:S494      SHTN1_S494__A0MZ66:S494
15      BICDL2:A1A5D9:S277     BICDL2_S277__A1A5D9:S277
16      BICDL2:A1A5D9:S36      BICDL2_S36__A1A5D9:S36
17      BICDL2:A1A5D9:T348     BICDL2_T348__A1A5D9:T348
18      C1orf226:A1L170:S198   C1orf226_S198__A1L170:S198
19      C1orf226:A1L170:S222   C1orf226_S222__A1L170:S222
20      C1orf226:A1L170:S244   C1orf226_S244__A1L170:S244
21      PLEKHG3:A1L390:S1037   PLEKHG3_S1037__A1L390:S1037
22      PLEKHG3:A1L390:S1040   PLEKHG3_S1040__A1L390:S1040
23      PLEKHG3:A1L390:S1081   PLEKHG3_S1081__A1L390:S1081
24      PLEKHG3:A1L390:S1154   PLEKHG3_S1154__A1L390:S1154
25      PLEKHG3:A1L390:S1169   PLEKHG3_S1169__A1L390:S1169
26      PLEKHG3:A1L390:S433    PLEKHG3_S433__A1L390:S433
27      PLEKHG3:A1L390:S488    PLEKHG3_S488__A1L390:S488
28      PLEKHG3:A1L390:S576    PLEKHG3_S576__A1L390:S576
29      PLEKHG3:A1L390:S577    PLEKHG3_S577__A1L390:S577
30      PLEKHG3:A1L390:S618    PLEKHG3_S618__A1L390:S618
⋮       ⋮                      ⋮
1224079 SLC4A4:Q9Y6R1:S262     SLC4A4_S262__Q9Y6R1:S262
1224080 SLC4A4:Q9Y6R1:S65      SLC4A4_S65__Q9Y6R1:S65
1224081 SLC4A4:Q9Y6R1:S68      SLC4A4_S68__Q9Y6R1:S68
1224082 SLC4A4:Q9Y6R1:S79      SLC4A4_S79__Q9Y6R1:S79
1224083 MAP3K4:Q9Y6R4:S1252    MAP3K4_S1252__Q9Y6R4:S1252
1224084 MAP3K4:Q9Y6R4:S431     MAP3K4_S431__Q9Y6R4:S431
1224085 MAP3K4:Q9Y6R4:S499     MAP3K4_S499__Q9Y6R4:S499
1224086 MAP3K4:Q9Y6R4:S66      MAP3K4_S66__Q9Y6R4:S66
1224087 MAP3K4:Q9Y6R4:T83      MAP3K4_T83__Q9Y6R4:T83
1224088 CCDC61:Q9Y6R9:S334     CCDC61_S334__Q9Y6R9:S334
1224089 CCDC61:Q9Y6R9:S336     CCDC61_S336__Q9Y6R9:S336
1224090 CCDC61:Q9Y6R9:S373     CCDC61_S373__Q9Y6R9:S373
1224091 CCDC61:Q9Y6R9:S376     CCDC61_S376__Q9Y6R9:S376
1224092 PCLO:Q9Y6V0:S772       PCLO_S772__Q9Y6V0:S772
1224093 WASF2:Q9Y6W5:T129      WASF2_T129__Q9Y6W5:T129
1224094 FAM169A:Q9Y6X4:S376    FAM169A_S376__Q9Y6X4:S376
1224095 FAM169A:Q9Y6X4:S378    FAM169A_S378__Q9Y6X4:S378
1224096 FAM169A:Q9Y6X4:S449    FAM169A_S449__Q9Y6X4:S449
1224097 FAM169A:Q9Y6X4:S526    FAM169A_S526__Q9Y6X4:S526
1224098 ZHX2:Q9Y6X8:T37        ZHX2_T37__Q9Y6X8:T37
1224099 MORC2:Q9Y6X9:S615      MORC2_S615__Q9Y6X9:S615
1224100 MORC2:Q9Y6X9:S725      MORC2_S725__Q9Y6X9:S725
1224101 MORC2:Q9Y6X9:S739      MORC2_S739__Q9Y6X9:S739
1224102 MORC2:Q9Y6X9:S743      MORC2_S743__Q9Y6X9:S743
1224103 MORC2:Q9Y6X9:S777      MORC2_S777__Q9Y6X9:S777
1224104 MORC2:Q9Y6X9:S779      MORC2_S779__Q9Y6X9:S779
1224105 IVNS1ABP:Q9Y6Y0:S277   IVNS1ABP_S277__Q9Y6Y0:S277
1224106 IVNS1ABP:Q9Y6Y0:S322   IVNS1ABP_S322__Q9Y6Y0:S322
1224107 IVNS1ABP:Q9Y6Y0:S326   IVNS1ABP_S326__Q9Y6Y0:S326
1224108 IVNS1ABP:Q9Y6Y0:S338   IVNS1ABP_S338__Q9Y6Y0:S338
        peptide_sequence              phosphosite run_id  peptide_intensity
1       UBA6_S36__A0AVT1:S36          S36         01CO005 -0.6170
2       ESYT2_S693__A0FGR8:S693       S693        01CO005 -0.9340
3       ESYT2_S704__A0FGR8:S704       S704        01CO005 -0.4740
4       ESYT2_S739__A0FGR8:S739       S739        01CO005 -1.3800
5       ESYT2_S755__A0FGR8:S755       S755        01CO005 -0.9565
6       ESYT2_S758__A0FGR8:S758       S758        01CO005 -0.9565
7       ESYT2_S761__A0FGR8:S761       S761        01CO005 -0.7120
8       ESYT2_T705__A0FGR8:T705       T705        01CO005 -0.4740
9       MED19_S226__A0JLT2:S226       S226        01CO005  0.1150
10      UHRF1BP1L_S1402__A0JNW5:S1402 S1402       01CO005 -0.9340
11      UHRF1BP1L_S891__A0JNW5:S891   S891        01CO005 -0.8680
12      UHRF1BP1L_S939__A0JNW5:S939   S939        01CO005 -1.4100
13      UHRF1BP1L_S989__A0JNW5:S989   S989        01CO005 -0.5020
14      SHTN1_S494__A0MZ66:S494       S494        01CO005 -0.3610
15      BICDL2_S277__A1A5D9:S277      S277        01CO005 -0.4480
16      BICDL2_S36__A1A5D9:S36        S36         01CO005 -1.4800
17      BICDL2_T348__A1A5D9:T348      T348        01CO005 -1.5230
18      C1orf226_S198__A1L170:S198    S198        01CO005 -0.3980
19      C1orf226_S222__A1L170:S222    S222        01CO005 -0.3640
20      C1orf226_S244__A1L170:S244    S244        01CO005 -1.1170
21      PLEKHG3_S1037__A1L390:S1037   S1037       01CO005 -0.5240
22      PLEKHG3_S1040__A1L390:S1040   S1040       01CO005 -0.1780
23      PLEKHG3_S1081__A1L390:S1081   S1081       01CO005 -0.7300
24      PLEKHG3_S1154__A1L390:S1154   S1154       01CO005 -0.2625
25      PLEKHG3_S1169__A1L390:S1169   S1169       01CO005 -0.4225
26      PLEKHG3_S433__A1L390:S433     S433        01CO005 -1.0040
27      PLEKHG3_S488__A1L390:S488     S488        01CO005  0.1780
28      PLEKHG3_S576__A1L390:S576     S576        01CO005 -0.1660
29      PLEKHG3_S577__A1L390:S577     S577        01CO005 -0.1660
30      PLEKHG3_S618__A1L390:S618     S618        01CO005 -1.3660
⋮       ⋮                             ⋮           ⋮       ⋮
1224079 SLC4A4_S262__Q9Y6R1:S262      S262        27CO004 -0.9320
1224080 SLC4A4_S65__Q9Y6R1:S65        S65         27CO004 -1.0260
1224081 SLC4A4_S68__Q9Y6R1:S68        S68         27CO004 -1.3690
1224082 SLC4A4_S79__Q9Y6R1:S79        S79         27CO004 -0.6830
1224083 MAP3K4_S1252__Q9Y6R4:S1252    S1252       27CO004  0.7250
1224084 MAP3K4_S431__Q9Y6R4:S431      S431        27CO004 -0.1390
1224085 MAP3K4_S499__Q9Y6R4:S499      S499        27CO004  0.6170
1224086 MAP3K4_S66__Q9Y6R4:S66        S66         27CO004  0.0050
1224087 MAP3K4_T83__Q9Y6R4:T83        T83         27CO004  0.0050
1224088 CCDC61_S334__Q9Y6R9:S334      S334        27CO004 -0.8325
1224089 CCDC61_S336__Q9Y6R9:S336      S336        27CO004 -1.0920
1224090 CCDC61_S373__Q9Y6R9:S373      S373        27CO004 -0.0710
1224091 CCDC61_S376__Q9Y6R9:S376      S376        27CO004 -0.1910
1224092 PCLO_S772__Q9Y6V0:S772        S772        27CO004  0.7160
1224093 WASF2_T129__Q9Y6W5:T129       T129        27CO004  0.2450
1224094 FAM169A_S376__Q9Y6X4:S376     S376        27CO004  0.1550
1224095 FAM169A_S378__Q9Y6X4:S378     S378        27CO004  0.1550
1224096 FAM169A_S449__Q9Y6X4:S449     S449        27CO004  0.1790
1224097 FAM169A_S526__Q9Y6X4:S526     S526        27CO004 -0.1130
1224098 ZHX2_T37__Q9Y6X8:T37          T37         27CO004 -0.4050
1224099 MORC2_S615__Q9Y6X9:S615       S615        27CO004 -0.6180
1224100 MORC2_S725__Q9Y6X9:S725       S725        27CO004  0.4370
1224101 MORC2_S739__Q9Y6X9:S739       S739        27CO004  0.2870
1224102 MORC2_S743__Q9Y6X9:S743       S743        27CO004  0.2870
1224103 MORC2_S777__Q9Y6X9:S777       S777        27CO004 -0.1460
1224104 MORC2_S779__Q9Y6X9:S779       S779        27CO004 -0.1585
1224105 IVNS1ABP_S277__Q9Y6Y0:S277    S277        27CO004  0.0330
1224106 IVNS1ABP_S322__Q9Y6Y0:S322    S322        27CO004 -0.9605
1224107 IVNS1ABP_S326__Q9Y6Y0:S326    S326        27CO004 -0.0540
1224108 IVNS1ABP_S338__Q9Y6Y0:S338    S338        27CO004  0.1090

In [6]:
proteo <- importProteoCCT(
    "./data/cptac-coad/Human__CPTAC_COAD__PNNL__Proteome__TMT__03_01_2017__BCM__Gene__PNNL_Tumor_TMT_UnsharedLogRatio.cct",
    fasta = "./tools/references/library.fasta"
)

Loading FASTA DB

Loading CCT data

In [7]:
proteo

       gene_id  protein_id peptide_id site_id
1      A1BG     P04217     P04217     A1BG:P04217:PA
2      A1CF     Q9NQ94     Q9NQ94     A1CF:Q9NQ94:PA
3      A2M      P01023     P01023     A2M:P01023:PA
4      AAAS     Q9NRG9     Q9NRG9     AAAS:Q9NRG9:PA
5      AACS     Q86V21     Q86V21     AACS:Q86V21:PA
6      AAGAB    Q6PD74     Q6PD74     AAGAB:Q6PD74:PA
7      AAK1     Q2M2I8     Q2M2I8     AAK1:Q2M2I8:PA
8      AAMDC    Q9H7C9     Q9H7C9     AAMDC:Q9H7C9:PA
9      AAMP     Q13685     Q13685     AAMP:Q13685:PA
10     AAR2     Q9Y312     Q9Y312     AAR2:Q9Y312:PA
11     AARS     P49588     P49588     AARS:P49588:PA
12     AARS2    Q5JTZ9     Q5JTZ9     AARS2:Q5JTZ9:PA
13     AASDHPPT Q9NRN7     Q9NRN7     AASDHPPT:Q9NRN7:PA
14     AASS     Q9UDR5     Q9UDR5     AASS:Q9UDR5:PA
15     AATF     Q9NY61     Q9NY61     AATF:Q9NY61:PA
16     ABAT     P80404     P80404     ABAT:P80404:PA
17     ABCA8    O94911     O94911     ABCA8:O94911:PA
18     ABCB1    P08183     P08183     ABCB1:P08183:PA
19     ABCB10   Q9NRK6     Q9NRK6     ABCB10:Q9NRK6:PA
20     ABCB6    Q9NP58     Q9NP58     ABCB6:Q9NP58:PA
21     ABCB7    O75027     O75027     ABCB7:O75027:PA
22     ABCB8    Q9NUT2     Q9NUT2     ABCB8:Q9NUT2:PA
23     ABCC1    P33527     P33527     ABCC1:P33527:PA
24     ABCC3    O15438     O15438     ABCC3:O15438:PA
25     ABCC4    O15439     O15439     ABCC4:O15439:PA
26     ABCD1    P33897     P33897     ABCD1:P33897:PA
27     ABCD3    P28288     P28288     ABCD3:P28288:PA
28     ABCE1    P61221     P61221     ABCE1:P61221:PA
29     ABCF1    Q8NE71     Q8NE71     ABCF1:Q8NE71:PA
30     ABCF2    Q9UG63     Q9UG63     ABCF2:Q9UG63:PA
⋮      ⋮        ⋮          ⋮          ⋮
762294 ZNF627   Q7L945     Q7L945     ZNF627:Q7L945:PA
762295 ZNF638   Q14966     Q14966     ZNF638:Q14966:PA
762296 ZNF662   Q6ZS27     Q6ZS27     ZNF662:Q6ZS27:PA
762297 ZNF687   Q8N1G0     Q8N1G0     ZNF687:Q8N1G0:PA
762298 ZNF703   Q9H7S9     Q9H7S9     ZNF703:Q9H7S9:PA
762299 ZNF705E  A8MWA4     A8MWA4     ZNF705E:A8MWA4:PA
762300 ZNF706   Q9Y5V0     Q9Y5V0     ZNF706:Q9Y5V0:PA
762301 ZNF74    Q16587     Q16587     ZNF74:Q16587:PA
762302 ZNF740   Q8NDX6     Q8NDX6     ZNF740:Q8NDX6:PA
762303 ZNF768   Q9H5H4     Q9H5H4     ZNF768:Q9H5H4:PA
762304 ZNF773   Q6PK81     Q6PK81     ZNF773:Q6PK81:PA
762305 ZNF787   Q6DD87     Q6DD87     ZNF787:Q6DD87:PA
762306 ZNF800   Q2TB10     Q2TB10     ZNF800:Q2TB10:PA
762307 ZNF808   Q8N4W9     Q8N4W9     ZNF808:Q8N4W9:PA
762308 ZNF830   Q96NB3     Q96NB3     ZNF830:Q96NB3:PA
762309 ZNF841   Q6ZN19     Q6ZN19     ZNF841:Q6ZN19:PA
762310 ZNF888   P0CJ79     P0CJ79     ZNF888:P0CJ79:PA
762311 ZNFX1    Q9P2E3     Q9P2E3     ZNFX1:Q9P2E3:PA
762312 ZNHIT2   Q9UHR6     Q9UHR6     ZNHIT2:Q9UHR6:PA
762313 ZNHIT3   Q15649     Q15649     ZNHIT3:Q15649:PA
762314 ZNHIT6   Q9NWK9     Q9NWK9     ZNHIT6:Q9NWK9:PA
762315 ZNRD1    Q9P1U0     Q9P1U0     ZNRD1:Q9P1U0:PA
762316 ZNRF2    Q8NHG8     Q8NHG8     ZNRF2:Q8NHG8:PA
762317 ZPR1     O75312     O75312     ZPR1:O75312:PA
762318 ZRANB2   O95218     O95218     ZRANB2:O95218:PA
762319 ZW10     O43264     O43264     ZW10:O43264:PA
762320 ZWILCH   Q9H900     Q9H900     ZWILCH:Q9H900:PA
762321 ZWINT    O95229     O95229     ZWINT:O95229:PA
762322 ZYX      Q15942     Q15942     ZYX:Q15942:PA
762323 ZZEF1    O43149     O43149     ZZEF1:O43149:PA
       modified_peptide_sequence peptide_sequence phosphosite run_id
1      P04217                    P04217           PA          01CO005
2      Q9NQ94                    Q9NQ94           PA          01CO005
3      P01023                    P01023           PA          01CO005
4      Q9NRG9                    Q9NRG9           PA          01CO005
5      Q86V21                    Q86V21           PA          01CO005
6      Q6PD74                    Q6PD74           PA          01CO005
7      Q2M2I8                    Q2M2I8           PA          01CO005
8      Q9H7C9                    Q9H7C9           PA          01CO005
9      Q13685                    Q13685           PA          01CO005
10     Q9Y312                    Q9Y312           PA          01CO005
11     P49588                    P49588           PA          01CO005
12     Q5JTZ9                    Q5JTZ9           PA          01CO005
13     Q9NRN7                    Q9NRN7           PA          01CO005
14     Q9UDR5                    Q9UDR5           PA          01CO005
15     Q9NY61                    Q9NY61           PA          01CO005
16     P80404                    P80404           PA          01CO005
17     O94911                    O94911           PA          01CO005
18     P08183                    P08183           PA          01CO005
19     Q9NRK6                    Q9NRK6           PA          01CO005
20     Q9NP58                    Q9NP58           PA          01CO005
21     O75027                    O75027           PA          01CO005
22     Q9NUT2                    Q9NUT2           PA          01CO005
23     P33527                    P33527           PA          01CO005
24     O15438                    O15438           PA          01CO005
25     O15439                    O15439           PA          01CO005
26     P33897                    P33897           PA          01CO005
27     P28288                    P28288           PA          01CO005
28     P61221                    P61221           PA          01CO005
29     Q8NE71                    Q8NE71           PA          01CO005
30     Q9UG63                    Q9UG63           PA          01CO005
⋮      ⋮                         ⋮                ⋮           ⋮
762294 Q7L945                    Q7L945           PA          27CO004
762295 Q14966                    Q14966           PA          27CO004
762296 Q6ZS27                    Q6ZS27           PA          27CO004
762297 Q8N1G0                    Q8N1G0           PA          27CO004
762298 Q9H7S9                    Q9H7S9           PA          27CO004
762299 A8MWA4                    A8MWA4           PA          27CO004
762300 Q9Y5V0                    Q9Y5V0           PA          27CO004
762301 Q16587                    Q16587           PA          27CO004
762302 Q8NDX6                    Q8NDX6           PA          27CO004
762303 Q9H5H4                    Q9H5H4           PA          27CO004
762304 Q6PK81                    Q6PK81           PA          27CO004
762305 Q6DD87                    Q6DD87           PA          27CO004
762306 Q2TB10                    Q2TB10           PA          27CO004
762307 Q8N4W9                    Q8N4W9           PA          27CO004
762308 Q96NB3                    Q96NB3           PA          27CO004
762309 Q6ZN19                    Q6ZN19           PA          27CO004
762310 P0CJ79                    P0CJ79           PA          27CO004
762311 Q9P2E3                    Q9P2E3           PA          27CO004
762312 Q9UHR6                    Q9UHR6           PA          27CO004
762313 Q15649                    Q15649           PA          27CO004
762314 Q9NWK9                    Q9NWK9           PA          27CO004
762315 Q9P1U0                    Q9P1U0           PA          27CO004
762316 Q8NHG8                    Q8NHG8           PA          27CO004
762317 O75312                    O75312           PA          27CO004
762318 O95218                    O95218           PA          27CO004
762319 O43264                    O43264           PA          27CO004
762320 Q9H900                    Q9H900           PA          27CO004
762321 O95229                    O95229           PA          27CO004
762322 Q15942                    Q15942           PA          27CO004
762323 O43149                    O43149           PA          27CO004
       peptide_intensity
1      -1.1000
2       0.3180
3      -0.4870
4       0.0995
5       0.1550
6       0.1690
7       0.0653
8      -0.1470
9       0.1140
10      0.3410
11     -0.1090
12      0.1230
13      0.2380
14          NA
15      0.0795
16      0.0311
17     -1.3000
18     -0.7510
19      0.1740
20          NA
21      0.3210
22     -0.2480
23     -0.1470
24      0.1320
25      0.1660
26     -0.0993
27     -0.3930
28      0.3450
29      0.3790
30     -0.1210
⋮      ⋮
762294      NA
762295  0.1960
762296      NA
762297  0.0236
762298 -0.6950
762299      NA
762300 -0.3190
762301      NA
762302 -0.1020
762303      NA
762304  0.1050
762305 -0.1590
762306  0.1980
762307      NA
762308      NA
762309 -0.5600
762310      NA
762311 -0.0086
762312 -0.1320
762313      NA
762314      NA
762315      NA
762316      NA
762317  0.1270
762318 -0.0992
762319  0.1900
762320 -0.2080
762321 -0.1980
762322 -0.2110
762323  0.0487

In [8]:
phospho[, run_id := as.character(run_id)]
proteo[, run_id := as.character(run_id)]

In [9]:
dir.create("./data/cptac-coad/processed")

In [10]:
saveRDS(phospho, "./data/cptac-coad/processed/CPTAC_COAD_phospho.rds")
saveRDS(proteo, "./data/cptac-coad/processed/CPTAC_COAD_proteo.rds")