# 00-2. Preprocessing (CPTAC-PDAC)

In [2]:
library(data.table)
library(vespa)

In [2]:
if (!dir.exists("./data/cptac-pdac")) {
  out <- system2(
    "bash",
    "./tools/scripts/cptac-pdac.sh",
    stdout = TRUE,
    stderr = TRUE
  )

  cat(out, sep = "\n")
}

In [3]:
if (!file.exists("./tools/references/library.fasta")) {
  out <- system2(
    "bash",
    "./tools/scripts/fasta.sh",
    stdout = TRUE,
    stderr = TRUE
  )

  cat(out, sep = "\n")
}

## Import data

In [45]:
phospho <- fread("./data/cptac-pdac/phosphoproteomics_site_level_MD_abundance_tumor.cct")

In [46]:
phospho

      Index             Gene
1     NP_000005.2_S928  A2M
2     NP_000009.1_S489  ACADVL
3     NP_000010.1_Y170  ACAT1
4     NP_000011.2_S160  ACVRL1
5     NP_000011.2_S161  ACVRL1
6     NP_000011.2_S495  ACVRL1
7     NP_000012.1_S366  PSEN1
8     NP_000012.1_S367  PSEN1
9     NP_000012.1_S43   PSEN1
10    NP_000013.2_T57   ADA
11    NP_000025.1_S132  ALDOA
12    NP_000025.1_S272  ALDOA
13    NP_000025.1_S276  ALDOA
14    NP_000025.1_S36   ALDOA
15    NP_000025.1_S39   ALDOA
16    NP_000025.1_S46   ALDOA
17    NP_000025.1_T37   ALDOA
18    NP_000025.1_T9    ALDOA
19    NP_000026.2_S161  ALDOB
20    NP_000026.2_S36   ALDOB
21    NP_000026.2_T227  ALDOB
22    NP_000026.2_T235  ALDOB
23    NP_000026.2_Y223  ALDOB
24    NP_000028.3_S1396 ANK1
25    NP_000028.3_S1428 ANK1
26    NP_000028.3_S1593 ANK1
27    NP_000028.3_S1686 ANK1
28    NP_000028.3_S1690 ANK1
29    NP_000028.3_S1696 ANK1
30    NP_000028.3_S4    ANK1
⋮     ⋮                 ⋮
51440 NP_998754.1_S531  RAPH1
51441 NP_998754.1_S532  RAPH1
51442 NP_998754.1_S533  RAPH1
51443 NP_998754.1_S54   RAPH1
51444 NP_998754.1_S571  RAPH1
51445 NP_998754.1_S610  RAPH1
51446 NP_998754.1_S827  RAPH1
51447 NP_998754.1_S845  RAPH1
51448 NP_998754.1_S853  RAPH1
51449 NP_998754.1_S856  RAPH1
51450 NP_998754.1_S880  RAPH1
51451 NP_998754.1_S894  RAPH1
51452 NP_998754.1_S979  RAPH1
51453 NP_998754.1_S983  RAPH1
51454 NP_998754.1_S996  RAPH1
51455 NP_998754.1_T1080 RAPH1
51456 NP_998754.1_T1097 RAPH1
51457 NP_998754.1_T1131 RAPH1
51458 NP_998754.1_T1134 RAPH1
51459 NP_998754.1_T1153 RAPH1
51460 NP_998754.1_T805  RAPH1
51461 NP_998754.1_T830  RAPH1
51462 NP_998754.1_T874  RAPH1
51463 NP_998771.3_S478  SLC16A12
51464 NP_998818.1_Y46   HJV
51465 NP_998839.1_S188  TPM2
51466 NP_998839.1_S206  TPM2
51467 NP_998839.1_S210  TPM2
51468 NP_998839.1_S215  TPM2
51469 NP_998839.1_S262  TPM2
      Peptide                                                        C3N-03884
1     ETTFNSLLCPSGGEVsEELSLK                                               NA
2     ELSGLGsALK                                                     13.84222
3     GSTPyGGVK                                                            NA
4     GLHSELGEsSLILK                                                       NA
5     GLHSELGESsLILK                                                       NA
6     ISNsPEKPK                                                            NA
7     AAVQELSsSILAGEDPEER                                                  NA
8     AAVQELSSsILAGEDPEER                                            18.93493
9     sLGHPEPLSNGRPQGNSR                                                   NA
10    RGIALPANTAEGLLNVIGMDKPLtLPDFLAK                                      NA
11    GVVPLAGTNGETTTQGLDGLsER                                        17.19216
12    TVPPAVTGITFLsGGQSEEEASINLNAINK                                       NA
13    TVPPAVTGITFLSGGQsEEEASINLNAINK                                 16.82438
14    GILAADEsTGSIAK                                                 23.08933
15    GILAADESTGsIAKR                                                22.97128
16    RLQsIGTENTEENRR                                                23.45205
17    GILAADEStGSIAK                                                       NA
18    PYQYPALtPEQK                                                   16.92633
19    IADQCPSsLAIQENANALAR                                           14.07573
20    GILAADEsVGTMGNR                                                      NA
21    ALNDHHVyLEGtLLKPNMVTAGHACTK;ALNDHHVyLEGtLLKPNMVtAGHACTK;       16.07362
22    ALNDHHVyLEGtLLKPNMVtAGHACTK                                          NA
23    ALNDHHVyLEGtLLKPNMVTAGHACTK;ALNDHHVyLEGtLLKPNMVtAGHACTK;       16.07362
24    YSILSESTPGsLSGTEQAEMK                                                NA
25    ELQFsVEDINR                                                    15.25923
26    AEDsDATGHEWK                                                   20.42945
27    ITHsPTVSQVTER                                                  23.37992
28    ITHsPTVsQVTER;ITHSPtVsQVTER;                                         NA
29    ITHSPTVSQVTERsQDR                                                    NA
30    PYsVGFR                                                        16.42333
⋮     ⋮                                                              ⋮
51440 RTESAYDWTSLSsSSIK                                                    NA
51441 RTESAYDWTSLSSsSIK                                                    NA
51442 RTESAYDWTSLSSSsIK                                                    NA
51443 RsPLRQETNMANFSYR                                               19.17913
51444 SQsIVSSVFSEAWK                                                 20.66344
51445 MESMNRPYTSLVPPLsPQPK                                           20.71070
51446 KQPAFPASYIPPsPPTPPVPVPPPTLPK                                         NA
51447 QQsFCAK;QQsFCAKPPPSPLSPVPSVVK;                                 21.01977
51448 QQSFCAKPPPsPLSPVPSVVK                                          16.69807
51449 QQSFCAKPPPSPLsPVPSVVK                                          18.77926
51450 QIASQFPPPPTPPAMEsQPLKPVPANVAPQsPPAVK                                 NA
51451 QIASQFPPPPTPPAMESQPLKPVPANVAPQsPPAVK;PVPANVAPQsPPAVK;          21.81392
51452 KPPPTPQRNsSIK                                                        NA
51453 sSSGAEHPEPK                                                          NA
51454 RPsVDSLVSK                                                     20.07987
51455 DSVVEFPSPPSDSDFPPPPPEtELPLPPIEIPAVFSGNTSPK                           NA
51456 DSVVEFPSPPSDSDFPPPPPETELPLPPIEIPAVFSGNtSPK                           NA
51457 RNDStRLTQAEISEQPTMATVVPQVPTSPK;RNDStRLTQAEISEQPTMATVVPQVPTSPK;       NA
51458 RNDSTRLtQAEISEQPTMATVVPQVPTSPK                                       NA
51459 RNDSTRLTQAEISEQPTMATVVPQVPtSPK;LTQAEISEQPTMATVVPQVPtSPK;       15.30463
51460 TVAPVVTQAAPPtPTPPVPPAK                                         19.10494
51461 KQPAFPASYIPPSPPtPPVPVPPPTLPK                                   17.20180
51462 QIASQFPPPPtPPAMESQPLKPVPANVAPQSPPAVK                                 NA
51463 TQLQFIAKEsDPK                                                        NA
51464 CNAEyVSSTLSLRGGGSSGALRGGGGGGR                                        NA
51465 AEVAEsR                                                              NA
51466 sLMASEEEYSTK                                                         NA
51467 SLMAsEEEYSTK                                                   16.31556
51468 SLMASEEEYsTK                                                         NA
51469 TIDDLEETLAsAK                                                  17.24692
      C3L-03123 C3L-01687 C3L-00589 C3L-00599 C3L-01054 C3L-03356 ⋯ C3N-01375
1           NA        NA        NA        NA        NA        NA  ⋯       NA
2     13.64339  14.25921  13.97222  13.83410        NA        NA  ⋯       NA
3           NA        NA        NA        NA        NA        NA  ⋯       NA
4           NA        NA        NA        NA        NA        NA  ⋯       NA
5           NA        NA        NA        NA        NA        NA  ⋯ 18.96619
6           NA        NA        NA        NA        NA        NA  ⋯       NA
7           NA        NA        NA        NA  16.51506  16.11122  ⋯ 16.73622
8     18.84214  18.73961  18.76958  17.95985        NA        NA  ⋯       NA
9           NA        NA        NA        NA  19.56398  20.97608  ⋯ 21.15073
10          NA        NA        NA        NA  15.57710  16.17124  ⋯       NA
11    17.19540  17.60238  17.50974  17.31387        NA        NA  ⋯       NA
12          NA        NA        NA        NA        NA        NA  ⋯       NA
13    18.67364  18.51300  18.10379  18.22537        NA        NA  ⋯       NA
14    22.70496  22.71271  22.32098  22.48322  22.24066  22.16453  ⋯       NA
15    22.70731  22.63120  22.73655  22.65788        NA        NA  ⋯ 22.05033
16    21.94781  23.61966  22.18115  21.54322  22.85512  22.08151  ⋯ 22.33728
17          NA        NA        NA        NA        NA        NA  ⋯       NA
18    16.64765  16.02985  16.75218  16.67190        NA        NA  ⋯       NA
19    14.18326  13.88647  14.03987  13.98372        NA        NA  ⋯       NA
20          NA        NA        NA        NA        NA        NA  ⋯       NA
21    16.08424  16.61848  16.47812  15.89248  16.08231  16.07072  ⋯       NA
22          NA        NA        NA        NA  15.93316  15.92157  ⋯       NA
23    16.08424  16.61848  16.47812  15.89248  16.08231  16.07072  ⋯       NA
24          NA        NA        NA        NA        NA        NA  ⋯       NA
25    14.98980  15.55074  15.34755  15.92498        NA        NA  ⋯       NA
26    19.05985  18.48275  18.08441  18.57555  18.43968  18.83530  ⋯       NA
27    22.39006  22.88295  22.40930  22.95498  22.58404  23.63253  ⋯ 23.57571
28          NA        NA        NA        NA        NA        NA  ⋯       NA
29          NA        NA        NA        NA        NA        NA  ⋯       NA
30    16.01938  15.57351  16.98760  15.98920        NA        NA  ⋯ 19.13121
⋮     ⋮         ⋮         ⋮         ⋮         ⋮         ⋮         ⋱ ⋮
51440       NA        NA        NA        NA        NA        NA  ⋯       NA
51441       NA        NA        NA        NA        NA        NA  ⋯       NA
51442       NA        NA        NA        NA        NA        NA  ⋯       NA
51443 20.92473  19.14858  19.56753  19.74089        NA        NA  ⋯ 20.89196
51444 20.09903  19.37035  20.74254  20.81028  20.74358  21.53638  ⋯ 21.20777
51445 20.13010  20.30716  20.54395  20.21211  21.17252  21.05568  ⋯ 21.04485
51446       NA        NA        NA        NA  15.10164  15.31392  ⋯       NA
51447 21.16760  22.20890  22.24125  21.79519  22.12125  21.99784  ⋯ 21.40946
51448 17.87303  17.88995  18.57620  17.35764        NA        NA  ⋯ 18.51118
51449 19.95462  20.02580  20.74270  20.07559  21.14107  21.12163  ⋯ 21.04710
51450       NA        NA        NA        NA  17.76562  17.95302  ⋯ 18.80967
51451 22.15546  22.19329  22.20080  21.80942  22.34759  22.01954  ⋯ 22.39973
51452       NA        NA        NA        NA  18.00710  17.57876  ⋯       NA
51453       NA        NA        NA        NA        NA        NA  ⋯ 16.52134
51454 19.91693  20.54733  20.11867  20.53901  21.01626  21.09251  ⋯ 21.58765
51455       NA        NA        NA        NA        NA        NA  ⋯       NA
51456       NA        NA        NA        NA        NA        NA  ⋯ 18.30007
51457       NA        NA        NA        NA        NA        NA  ⋯       NA
51458       NA        NA        NA        NA        NA        NA  ⋯       NA
51459 14.97771  15.95697  15.98557  15.52542        NA        NA  ⋯       NA
51460 18.67653  19.08563  18.52023  18.79177  19.35654  18.94370  ⋯ 19.67778
51461 17.95611  17.74161  18.02154  18.25540  17.80977  17.77318  ⋯       NA
51462       NA        NA        NA        NA  14.46405  14.34329  ⋯       NA
51463       NA        NA        NA        NA        NA        NA  ⋯ 15.34683
51464       NA        NA        NA        NA        NA        NA  ⋯       NA
51465       NA        NA        NA        NA        NA        NA  ⋯       NA
51466       NA        NA        NA        NA        NA        NA  ⋯       NA
51467 16.44170  16.12190  17.56186  17.39792        NA        NA  ⋯       NA
51468       NA        NA        NA        NA  20.17905  19.99859  ⋯       NA
51469 17.27558  17.34957  18.00456  19.31675  17.84790  17.63821  ⋯       NA
      C3N-01381 C3L-00401 C3L-02118 C3N-00511 C3L-02613 C3N-00512 C3L-02899
1           NA        NA        NA        NA        NA        NA        NA
2           NA        NA        NA        NA        NA        NA        NA
3           NA        NA        NA        NA        NA        NA        NA
4           NA        NA        NA  18.01134  18.82855  18.32407  18.50001
5     18.31143  17.44497  18.68298        NA        NA        NA        NA
6           NA        NA        NA        NA        NA        NA        NA
7     16.74612  17.00373  16.51724        NA        NA        NA        NA
8           NA        NA        NA        NA        NA        NA        NA
9     20.68819  19.97195  21.41541  21.54934  22.31834  20.99347  21.68634
10          NA        NA        NA        NA        NA        NA        NA
11          NA        NA        NA        NA        NA        NA        NA
12          NA        NA        NA  16.36583  16.31755  16.80613  17.19484
13          NA        NA        NA        NA        NA        NA        NA
14          NA        NA        NA  22.26267  22.58524  22.68030  23.00164
15    22.37691  21.46720  22.00036        NA        NA        NA        NA
16    22.31411  22.63302  22.45414  22.54883  23.29616  21.90895  23.39795
17          NA        NA        NA        NA        NA        NA        NA
18          NA        NA        NA        NA        NA        NA        NA
19          NA        NA        NA        NA        NA        NA        NA
20          NA        NA        NA        NA        NA        NA        NA
21          NA        NA        NA        NA        NA        NA        NA
22          NA        NA        NA        NA        NA        NA        NA
23          NA        NA        NA        NA        NA        NA        NA
24          NA        NA        NA        NA        NA        NA        NA
25          NA        NA        NA        NA        NA        NA        NA
26          NA        NA        NA        NA        NA        NA        NA
27    22.86835  23.04516  22.79444  23.23574  22.94430  22.92334  22.95773
28          NA        NA        NA        NA        NA        NA        NA
29          NA        NA        NA        NA        NA        NA        NA
30    15.94171  17.11324  16.51757  18.69888  15.70376  14.57985  16.59092
⋮     ⋮         ⋮         ⋮         ⋮         ⋮         ⋮         ⋮
51440       NA        NA        NA        NA        NA        NA        NA
51441       NA        NA        NA        NA        NA        NA        NA
51442       NA        NA        NA        NA        NA        NA        NA
51443 18.33283  18.41564  19.24539  20.57522  20.76181  18.45523  21.00079
51444 18.74970  18.28759  20.70935  21.60191  22.10428  21.40014  21.47316
51445 20.68897  19.74720  20.84512  21.43932  22.06293  20.62923  20.43676
51446       NA        NA        NA        NA        NA        NA        NA
51447 21.34636  19.75461  22.30254  22.28583  22.19690  22.01115  22.13938
51448 17.83590  17.22163  18.30953  19.81299  19.20602  18.93936  18.72967
51449 19.94401  19.66580  20.77644  21.24416  22.50758  20.92399  21.02934
51450 16.80986  16.58907  18.00582  18.69205  19.38616  17.77212  17.45622
51451 21.65651  21.88404  22.12137  22.45848  23.21893  22.08189  21.74044
51452       NA        NA        NA        NA        NA        NA        NA
51453 17.30913  16.94647  17.43822  17.09920  16.70361  16.49210  16.44580
51454 20.62960  20.79088  21.30433  20.95510  21.79030  20.87173  20.88784
51455       NA        NA        NA        NA        NA        NA        NA
51456 17.28870  15.69167  17.85546  18.54390  19.38465  17.88207  17.98912
51457       NA        NA        NA        NA        NA        NA        NA
51458       NA        NA        NA        NA        NA        NA        NA
51459       NA        NA        NA        NA        NA        NA        NA
51460 19.27043  18.07313  19.63295  20.34022  21.00841  19.37219  19.98287
51461       NA        NA        NA  18.69362  18.68614  18.43991  18.26017
51462       NA        NA        NA        NA        NA        NA        NA
51463 17.59929  16.77225  15.93846  15.48286  14.87635  16.67601  15.04950
51464       NA        NA        NA        NA        NA        NA        NA
51465       NA        NA        NA        NA        NA        NA        NA
51466       NA        NA        NA        NA        NA        NA        NA
51467       NA        NA        NA        NA        NA        NA        NA
51468       NA        NA        NA  18.39440  19.00514  20.70686  20.21299
51469       NA        NA        NA        NA        NA        NA        NA
      C3N-03006 C3N-03069
1           NA        NA
2           NA        NA
3           NA        NA
4     18.10603  18.59428
5           NA        NA
6           NA        NA
7           NA        NA
8           NA        NA
9     21.15257  21.09441
10          NA        NA
11          NA        NA
12    16.27449  16.82968
13          NA        NA
14    22.22551  23.30295
15          NA        NA
16    21.90952  24.08430
17          NA        NA
18          NA        NA
19          NA        NA
20          NA        NA
21          NA        NA
22          NA        NA
23          NA        NA
24          NA        NA
25          NA        NA
26          NA        NA
27    22.79005  23.28026
28          NA        NA
29          NA        NA
30    15.67391  18.44558
⋮     ⋮         ⋮
51440       NA        NA
51441       NA        NA
51442       NA        NA
51443 19.85307  20.28215
51444 22.64222  21.77909
51445 21.13909  20.44768
51446       NA        NA
51447 21.56316  21.89734
51448 19.26590  18.15067
51449 21.32399  20.32551
51450 18.35321  17.96467
51451 22.26503  21.98345
51452       NA        NA
51453 16.57034  16.71721
51454 21.06130  21.72189
51455       NA        NA
51456 18.33415  18.34546
51457       NA        NA
51458       NA        NA
51459       NA        NA
51460 20.11256  20.11108
51461 18.28098  17.84718
51462       NA        NA
51463 16.27055  14.74563
51464       NA        NA
51465       NA        NA
51466       NA        NA
51467       NA        NA
51468 20.22241  21.31457
51469       NA        NA

In [47]:
sample_cols <- setdiff(
  names(phospho),
  c("Index", "Gene", "Peptide")
)

for (j in sample_cols) {
  set(
    phospho,
    i = which(!is.na(phospho[[j]]) & !is.finite(phospho[[j]])),
    j = j,
    value = NA_real_
  )
}

phospho[, row_id := .I]
phospho[, gene_id := Gene]
phospho[, refseq_id := sub("_[STY][0-9]+$", "", Index)]
phospho[, refseq_phosphosite := sub("^.*_([STY][0-9]+)$", "\\1", Index)]

phospho[, modified_peptide_sequence := Peptide]
phospho[, peptide_sequence := toupper(Peptide)]

In [48]:
phospho_pep <- phospho[
  ,
  .(
    peptide_candidate = unlist(strsplit(Peptide, ";", fixed = TRUE))
  ),
  by = .(
    row_id,
    gene_id,
    refseq_id,
    refseq_phosphosite
  )
]

phospho_pep[, peptide_candidate := trimws(peptide_candidate)]
phospho_pep <- phospho_pep[peptide_candidate != ""]

phospho_pep[
  ,
  n_mods := lengths(
    regmatches(
      peptide_candidate,
      gregexpr("[sty]", peptide_candidate)
    )
  )
]

table(phospho_pep$n_mods)

    1     2     3
50714  6409  3168

In [49]:
phospho_pep <- phospho_pep[n_mods == 1]

In [50]:
phospho_pep[
  ,
  mod_pos_in_peptide := regexpr("[sty]", peptide_candidate)
]

phospho_pep[
  ,
  mod_aa := toupper(
    substr(
      peptide_candidate,
      mod_pos_in_peptide,
      mod_pos_in_peptide
    )
  )
]

phospho_pep[
  ,
  peptide_sequence := toupper(peptide_candidate)
]

phospho_pep[
  ,
  modified_peptide_sequence := peptide_candidate
]

head(phospho_pep)

  row_id gene_id refseq_id   refseq_phosphosite peptide_candidate      n_mods
1 1      A2M     NP_000005.2 S928               ETTFNSLLCPSGGEVsEELSLK 1
2 2      ACADVL  NP_000009.1 S489               ELSGLGsALK             1
3 3      ACAT1   NP_000010.1 Y170               GSTPyGGVK              1
4 4      ACVRL1  NP_000011.2 S160               GLHSELGEsSLILK         1
5 5      ACVRL1  NP_000011.2 S161               GLHSELGESsLILK         1
6 6      ACVRL1  NP_000011.2 S495               ISNsPEKPK              1
  mod_pos_in_peptide mod_aa peptide_sequence       modified_peptide_sequence
1 16                 S      ETTFNSLLCPSGGEVSEELSLK ETTFNSLLCPSGGEVsEELSLK
2  7                 S      ELSGLGSALK             ELSGLGsALK
3  5                 Y      GSTPYGGVK              GSTPyGGVK
4  9                 S      GLHSELGESSLILK         GLHSELGEsSLILK
5 10                 S      GLHSELGESSLILK         GLHSELGESsLILK
6  4                 S      ISNSPEKPK              ISNsPEKPK

In [51]:
fasta_lines <- readLines("tools/references/library.fasta")

header_idx <- grep("^>", fasta_lines)

fasta_dt <- data.table(
  header = fasta_lines[header_idx],
  start = header_idx + 1,
  end = c(header_idx[-1] - 1, length(fasta_lines))
)

fasta_dt[
  ,
  sequence := vapply(
    seq_len(.N),
    function(i) paste0(fasta_lines[start[i]:end[i]], collapse = ""),
    character(1)
  )
]

fasta_dt[
  ,
  protein_id_uniprot := sub("^>[^|]*\\|([^|]+)\\|.*", "\\1", header)
]

fasta_dt[
  ,
  gene_id := ifelse(
    grepl(" GN=", header),
    sub(".* GN=([^ ]+).*", "\\1", header),
    NA_character_
  )
]

fasta_dt <- fasta_dt[!is.na(gene_id)]
fasta_dt[, is_sp := grepl("^>sp\\|", header)]

head(fasta_dt)

  header
1 >sp|Q6ZSK4|NTAS1_HUMAN Putative uncharacterized protein NTM-AS1 OS=Homo sapiens OX=9606 GN=NTM-AS1 PE=5 SV=1
2 >sp|Q9Y263|PLAP_HUMAN Phospholipase A-2-activating protein OS=Homo sapiens OX=9606 GN=PLAA PE=1 SV=2
3 >sp|Q96RE7|NACC1_HUMAN Nucleus accumbens-associated protein 1 OS=Homo sapiens OX=9606 GN=NACC1 PE=1 SV=1
4 >sp|O43312|MTSS1_HUMAN Protein MTSS 1 OS=Homo sapiens OX=9606 GN=MTSS1 PE=1 SV=2
5 >sp|Q9NP80|PLPL8_HUMAN Calcium-independent phospholipase A2-gamma OS=Homo sapiens OX=9606 GN=PNPLA8 PE=1 SV=1
6 >sp|Q15319|PO4F3_HUMAN POU domain, class 4, transcription factor 3 OS=Homo sapiens OX=9606 GN=POU4F3 PE=1 SV=1
  start end
1  2     4
2  6    19
3 21    29
4 31    43
5 45    58
6 60    65
  sequence
1 MKGQEGIRGEGCTDPEIKASPQMWAARFRGMRSRFSPLFSQATEMGPRVSAGWCLSGGGRKVSSLQGDFPPGGFWALSNDSALSLPPLSLPHPHPLRPPGLGVNEFTQGLHPPLHPAASVFQTCFYRKPHYCSTLRPTTT
2 MTSGATRYRLSCSLRGHELDVRGLVCCAYPPGAFVSVSRDRTTRLWAPDSPNRSFTEMHCMSGHSNFVSCVCIIPSSDIYPHGLIATGGNDHNICIFSLDSPMPLYILKGHKNTVCSLSSGKFGTLLSGSWDTTAKVWLNDKCMMTLQGHTAAVWAVKILPEQGLMLTGSADKTVKLWKAGRCERTFSGHEDCVRGLAILSETEFLSCANDASIRRWQITGECLEVYYGHTNYIYSISVFPNCRDFVTTAEDRSLRIWKHGECAQTIRLPAQSIWCCCVLDNGDIVVGASDGIIRVFTESEDRTASAEEIKAFEKELSHATIDSKTGDLGDINAEQLPGREHLNEPGTREGQTRLIRDGEKVEAYQWSVSEGRWIKIGDVVGSSGANQQTSGKVLYEGKEFDYVFSIDVNEGGPSYKLPYNTSDDPWLTAYNFLQKNDLNPMFLDQVAKFIIDNTKGQMLGLGNPSFSDPFTGGGRYVPGSSGSSNTLPTADPFTGAGRYVPGSASMGTTMAGVDPFTGNSAYRSAASKTMNIYFPKKEAVTFDQANPTQILGKLKELNGTAPEEKKLTEDDLILLEKILSLICNSSSEKPTVQQLQILWKAINCPEDIVFPALDILRLSIKHPSVNENFCNEKEGAQFSSHLINLLNPKGKPANQLLALRTFCNCFVGQAGQKLMMSQRESLMSHAIELKSGSNKNIHIALATLALNYSVCFHKDHNIEGKAQCLSLISTILEVVQDLEATFRLLVALGTLISDDSNAVQLAKSLGVDSQIKKYSSVSEPAKVSECCRFILNLL
3 MAQTLQMEIPNFGNSILECLNEQRLQGLYCDVSVVVKGHAFKAHRAVLAASSSYFRDLFNNSRSAVVELPAAVQPQSFQQILSFCYTGRLSMNVGDQFLLMYTAGFLQIQEIMEKGTEFFLKVSSPSCDSQGLHAEEAPSSEPQSPVAQTSGWPACSTPLPLVSRVKTEQQESDSVQCMPVAKRLWDSGQKEAGGGGNGSRKMAKFSTPDLAANRPHQPPPPQQAPVVAAAQPAVAAGAGQPAGGVAAAGGVVSGPSTSERTSPGTSSAYTSDSPGSYHNEEDEEEDGGEEGMDEQYRQICNMYTMYSMMNVGQTAEKVEALPEQVAPESRNRIRVRQDLASLPAELINQIGNRCHPKLYDEGDPSEKLELVTGTNVYITRAQLMNCHVSAGTRHKVLLRRLLASFFDRNTLANSCGTGIRSSTNDPRRKPLDSRVLHAVKYYCQNFAPNFKESEMNAIAADMCTNARRVVRKSWMPKVKVLKAEDDAYTTFISETGKIEPDMMGVEHGFETASHEGEAGPSAEALQ
4 MEAVIEKECSALGGLFQTIISDMKGSYPVWEDFINKAGKLQSQLRTTVVAAAAFLDAFQKVADMATNTRGGTREIGSALTRMCMRHRSIEAKLRQFSSALIDCLINPLQEQMEEWKKVANQLDKDHAKEYKKARQEIKKKSSDTLKLQKKAKKGRGDIQPQLDSALQDVNDKYLLLEETEKQAVRKALIEERGRFCTFISMLRPVIEEEISMLGEITHLQTISEDLKSLTMDPHKLPSSSEQVILDLKGSDYSWSYQTPPSSPSTTMSRKSSVCSSLNSVNSSDSRSSGSHSHSPSSHYRYRSSNLAQQAPVRLSSVSSHDSGFISQDAFQSKSPSPMPPEAPNQLSNGFSHYSLSSESHVGPTGAGLFPHCLPASRLLPRVTSVHLPDYAHYYTIGPGMFPSSQIPSWKDWAKPGPYDQPLVNTLQRRKEKREPDPNGGGPTTASGPPAAAEEAQRPRSMTVSAATRPGEEMEACEELALALSRGLQLDTQRSSRDSLQCSSGYSTQTTTPCCSEDTIPSQVSDYDYFSVSGDQEADQQEFDKSSTIPRNSDISQSYRRMFQAKRPASTAGLPTTLGPAMVTPGVATIRRTPSTKPSVRRGTIGAGPIPIKTPVIPVKTPTVPDLPGVLPAPPDGPEERGEHSPESPSVGEGPQGVTSMPSSMWSGQASVNPPLPGPKPSIPEEHRQAIPESEAEDQEREPPSATVSPGQIPESDPADLSPRDTPQGEDMLNAIRRGVKLKKTTTNDRSAPRFS
5 MSINLTVDIYIYLLSNARSVCGKQRSKQLYFLFSPKHYWRISHISLQRGFHTNIIRCKWTKSEAHSCSKHCYSPSNHGLHIGILKLSTSAPKGLTKVNICMSRIKSTLNSVSKAVFGNQNEMISRLAQFKPSSQILRKVSDSGWLKQKNIKQAIKSLKKYSDKSAEKSPFPEEKSHIIDKEEDIGKRSLFHYTSSITTKFGDSFYFLSNHINSYFKRKEKMSQQKENEHFRDKSELEDKKVEEGKLRSPDPGILAYKPGSESVHTVDKPTSPSAIPDVLQVSTKQSIANFLSRPTEGVQALVGGYIGGLVPKLKYDSKSQSEEQEEPAKTDQAVSKDRNAEEKKRLSLQREKIIARVSIDNRTRALVQALRRTTDPKLCITRVEELTFHLLEFPEGKGVAVKERIIPYLLRLRQIKDETLQAAVREILALIGYVDPVKGRGIRILSIDGGGTRGVVALQTLRKLVELTQKPVHQLFDYICGVSTGAILAFMLGLFHMPLDECEELYRKLGSDVFSQNVIVGTVKMSWSHAFYDSQTWENILKDRMGSALMIETARNPTCPKVAAVSTIVNRGITPKAFVFRNYGHFPGINSHYLGGCQYKMWQAIRASSAAPGYFAEYALGNDLHQDGGLLLNNPSALAMHECKCLWPDVPLECIVSLGTGRYESDVRNTVTYTSLKTKLSNVINSATDTEEVHIMLDGLLPPDTYFRFNPVMCENIPLDESRNEKLDQLQLEGLKYIERNEQKMKKVAKILSQEKTTLQKINDWIKLKTDMYEGLPFFSKL
6 MMAMNSKQPFGMHPVLQEPKFSSLHSGSEAMRRVCLPAPQLQGNIFGSFDESLLARAEALAAVDIVSHGKNHPFKPDATYHTMSSVPCTSTSSTVPISHPAALTSHPHHAVHQGLEGDLLEHISPTLSVSGLGAPEHSVMPAQIHPHHLGAMGHLHQAMGMSHPHTVAPHSAMPACLSDVESDPRELEAFAERFKQRRIKLGVTQADVGAALANLKIPGVGSLSQSTICRFESLTLSHNNMIALKPVLQAWLEEAEAAYREKNSKPELFNGSERKRKRTSIAAPEKRSLEAYFAIQPRPSSEKIAAIAEKLDLKKNVVRVWFCNQRQKQKRMKYSAVH
  protein_id_uniprot gene_id is_sp
1 Q6ZSK4             NTM-AS1 TRUE
2 Q9Y263             PLAA    TRUE
3 Q96RE7             NACC1   TRUE
4 O43312             MTSS1   TRUE
5 Q9NP80             PNPLA8  TRUE
6 Q15319             POU4F3  TRUE

In [52]:
cand <- merge(
  phospho_pep,
  fasta_dt[
    ,
    .(
      gene_id,
      protein_id_uniprot,
      fasta_sequence = sequence,
      is_sp
    )
  ],
  by = "gene_id",
  allow.cartesian = TRUE
)

cand[
  ,
  peptide_start := mapply(
    function(pat, seq) {
      regexpr(pat, seq, fixed = TRUE)[1]
    },
    peptide_sequence,
    fasta_sequence
  )
]

cand <- cand[peptide_start > 0]

cat("candidate matches:", nrow(cand), "\n")
cat("mapped original rows:", uniqueN(cand$row_id), "\n")

candidate matches: 48880
mapped original rows: 43351

In [53]:
cand[
  ,
  uniprot_site_pos := peptide_start + mod_pos_in_peptide - 1
]

cand[
  ,
  uniprot_site_aa := substr(
    fasta_sequence,
    uniprot_site_pos,
    uniprot_site_pos
  )
]

cand <- cand[mod_aa == uniprot_site_aa]

cat("AA-consistent matches:", nrow(cand), "\n")
cat("AA-consistent original rows:", uniqueN(cand$row_id), "\n")

cand[
  ,
  phosphosite := paste0(
    uniprot_site_aa,
    uniprot_site_pos
  )
]

AA-consistent matches: 48880
AA-consistent original rows: 43351

In [54]:
setorder(cand, row_id, -is_sp, protein_id_uniprot)

cand_best <- cand[
  ,
  .SD[1],
  by = row_id
]

cat("final mapped phospho rows:", nrow(cand_best), "\n")

head(
  cand_best[
    ,
    .(
      gene_id,
      refseq_id,
      refseq_phosphosite,
      protein_id_uniprot,
      phosphosite,
      modified_peptide_sequence,
      peptide_sequence
    )
  ],
  20
)

final mapped phospho rows: 43351

   gene_id refseq_id   refseq_phosphosite protein_id_uniprot phosphosite
1  A2M     NP_000005.2 S928               P01023             S928
2  ACADVL  NP_000009.1 S489               P49748             S489
3  ACAT1   NP_000010.1 Y170               P24752             Y170
4  ACVRL1  NP_000011.2 S160               P37023             S160
5  ACVRL1  NP_000011.2 S161               P37023             S161
6  ACVRL1  NP_000011.2 S495               P37023             S495
7  PSEN1   NP_000012.1 S366               P49768             S366
8  PSEN1   NP_000012.1 S367               P49768             S367
9  PSEN1   NP_000012.1 S43                P49768             S43
10 ADA     NP_000013.2 T57                P00813             T57
11 ALDOA   NP_000025.1 S132               P04075             S132
12 ALDOA   NP_000025.1 S272               P04075             S272
13 ALDOA   NP_000025.1 S276               P04075             S276
14 ALDOA   NP_000025.1 S36                P04075             S36
15 ALDOA   NP_000025.1 S39                P04075             S39
16 ALDOA   NP_000025.1 S46                P04075             S46
17 ALDOA   NP_000025.1 T37                P04075             T37
18 ALDOA   NP_000025.1 T9                 P04075             T9
19 ALDOB   NP_000026.2 S161               P05062             S161
20 ALDOB   NP_000026.2 S36                P05062             S36
   modified_peptide_sequence       peptide_sequence
1  ETTFNSLLCPSGGEVsEELSLK          ETTFNSLLCPSGGEVSEELSLK
2  ELSGLGsALK                      ELSGLGSALK
3  GSTPyGGVK                       GSTPYGGVK
4  GLHSELGEsSLILK                  GLHSELGESSLILK
5  GLHSELGESsLILK                  GLHSELGESSLILK
6  ISNsPEKPK                       ISNSPEKPK
7  AAVQELSsSILAGEDPEER             AAVQELSSSILAGEDPEER
8  AAVQELSSsILAGEDPEER             AAVQELSSSILAGEDPEER
9  sLGHPEPLSNGRPQGNSR              SLGHPEPLSNGRPQGNSR
10 RGIALPANTAEGLLNVIGMDKPLtLPDFLAK RGIALPANTAEGLLNVIGMDKPLTLPDFLAK
11 GVVPLAGTNGETTTQGLDGLsER         GVVPLAGTNGETTTQGLDGLSER
12 TVPPAVTGITFLsGGQSEEEASINLNAINK  TVPPAVTGITFLSGGQSEEEASINLNAINK
13 TVPPAVTGITFLSGGQsEEEASINLNAINK  TVPPAVTGITFLSGGQSEEEASINLNAINK
14 GILAADEsTGSIAK                  GILAADESTGSIAK
15 GILAADESTGsIAKR                 GILAADESTGSIAKR
16 RLQsIGTENTEENRR                 RLQSIGTENTEENRR
17 GILAADEStGSIAK                  GILAADESTGSIAK
18 PYQYPALtPEQK                    PYQYPALTPEQK
19 IADQCPSsLAIQENANALAR            IADQCPSSLAIQENANALAR
20 GILAADEsVGTMGNR                 GILAADESVGTMGNR

In [57]:
map_phospho <- cand_best[
  ,
  .(
    row_id,
    protein_id = protein_id_uniprot,
    phosphosite,
    modified_peptide_sequence,
    peptide_sequence
  )
]

drop_cols <- intersect(
  c("protein_id", "phosphosite", "site_id", "peptide_id",
    "modified_peptide_sequence", "peptide_sequence"),
  names(phospho)
)

phospho_base <- copy(phospho)

if (length(drop_cols) > 0) {
  phospho_base[, (drop_cols) := NULL]
}

phospho_mapped <- merge(
  phospho_base,
  map_phospho,
  by = "row_id",
  all.x = FALSE
)

phospho_mapped[, site_id := paste(gene_id, protein_id, phosphosite, sep = ":")]

phospho_mapped[
  ,
  peptide_id := paste(
    protein_id,
    phosphosite,
    modified_peptide_sequence,
    sep = "__"
  )
]

dim(phospho)
dim(phospho_mapped)

head(
  phospho_mapped[
    ,
    .(
      gene_id,
      refseq_id,
      refseq_phosphosite,
      protein_id,
      phosphosite,
      site_id,
      modified_peptide_sequence
    )
  ],
  20
)

[1] 51469   149

[1] 43351   153

   gene_id refseq_id   refseq_phosphosite protein_id phosphosite
1  A2M     NP_000005.2 S928               P01023     S928
2  ACADVL  NP_000009.1 S489               P49748     S489
3  ACAT1   NP_000010.1 Y170               P24752     Y170
4  ACVRL1  NP_000011.2 S160               P37023     S160
5  ACVRL1  NP_000011.2 S161               P37023     S161
6  ACVRL1  NP_000011.2 S495               P37023     S495
7  PSEN1   NP_000012.1 S366               P49768     S366
8  PSEN1   NP_000012.1 S367               P49768     S367
9  PSEN1   NP_000012.1 S43                P49768     S43
10 ADA     NP_000013.2 T57                P00813     T57
11 ALDOA   NP_000025.1 S132               P04075     S132
12 ALDOA   NP_000025.1 S272               P04075     S272
13 ALDOA   NP_000025.1 S276               P04075     S276
14 ALDOA   NP_000025.1 S36                P04075     S36
15 ALDOA   NP_000025.1 S39                P04075     S39
16 ALDOA   NP_000025.1 S46                P04075     S46
17 ALDOA   NP_000025.1 T37                P04075     T37
18 ALDOA   NP_000025.1 T9                 P04075     T9
19 ALDOB   NP_000026.2 S161               P05062     S161
20 ALDOB   NP_000026.2 S36                P05062     S36
   site_id            modified_peptide_sequence
1  A2M:P01023:S928    ETTFNSLLCPSGGEVsEELSLK
2  ACADVL:P49748:S489 ELSGLGsALK
3  ACAT1:P24752:Y170  GSTPyGGVK
4  ACVRL1:P37023:S160 GLHSELGEsSLILK
5  ACVRL1:P37023:S161 GLHSELGESsLILK
6  ACVRL1:P37023:S495 ISNsPEKPK
7  PSEN1:P49768:S366  AAVQELSsSILAGEDPEER
8  PSEN1:P49768:S367  AAVQELSSsILAGEDPEER
9  PSEN1:P49768:S43   sLGHPEPLSNGRPQGNSR
10 ADA:P00813:T57     RGIALPANTAEGLLNVIGMDKPLtLPDFLAK
11 ALDOA:P04075:S132  GVVPLAGTNGETTTQGLDGLsER
12 ALDOA:P04075:S272  TVPPAVTGITFLsGGQSEEEASINLNAINK
13 ALDOA:P04075:S276  TVPPAVTGITFLSGGQsEEEASINLNAINK
14 ALDOA:P04075:S36   GILAADEsTGSIAK
15 ALDOA:P04075:S39   GILAADESTGsIAKR
16 ALDOA:P04075:S46   RLQsIGTENTEENRR
17 ALDOA:P04075:T37   GILAADEStGSIAK
18 ALDOA:P04075:T9    PYQYPALtPEQK
19 ALDOB:P05062:S161  IADQCPSsLAIQENANALAR
20 ALDOB:P05062:S36   GILAADEsVGTMGNR

In [58]:
phospho_long <- melt(
  phospho_mapped,
  id.vars = c(
    "gene_id",
    "protein_id",
    "peptide_id",
    "site_id",
    "modified_peptide_sequence",
    "peptide_sequence",
    "phosphosite"
  ),
  measure.vars = sample_cols,
  variable.name = "run_id",
  value.name = "peptide_intensity",
  variable.factor = FALSE,
  na.rm = TRUE
)

phospho_long[, run_id := as.character(run_id)]
phospho_long[, peptide_intensity := as.numeric(peptide_intensity)]

phospho_long <- phospho_long[
  !is.na(peptide_intensity) & is.finite(peptide_intensity)
]

phospho_long <- phospho_long[
  ,
  .(
    gene_id,
    protein_id,
    peptide_id,
    site_id,
    modified_peptide_sequence,
    peptide_sequence,
    phosphosite,
    run_id,
    peptide_intensity
  )
]

dim(phospho_long)
head(phospho_long)

[1] 2272580       9

  gene_id protein_id peptide_id
1 ACADVL  P49748     P49748__S489__ELSGLGsALK
2 PSEN1   P49768     P49768__S367__AAVQELSSsILAGEDPEER
3 ALDOA   P04075     P04075__S132__GVVPLAGTNGETTTQGLDGLsER
4 ALDOA   P04075     P04075__S276__TVPPAVTGITFLSGGQsEEEASINLNAINK
5 ALDOA   P04075     P04075__S36__GILAADEsTGSIAK
6 ALDOA   P04075     P04075__S39__GILAADESTGsIAKR
  site_id            modified_peptide_sequence
1 ACADVL:P49748:S489 ELSGLGsALK
2 PSEN1:P49768:S367  AAVQELSSsILAGEDPEER
3 ALDOA:P04075:S132  GVVPLAGTNGETTTQGLDGLsER
4 ALDOA:P04075:S276  TVPPAVTGITFLSGGQsEEEASINLNAINK
5 ALDOA:P04075:S36   GILAADEsTGSIAK
6 ALDOA:P04075:S39   GILAADESTGsIAKR
  peptide_sequence               phosphosite run_id    peptide_intensity
1 ELSGLGSALK                     S489        C3N-03884 13.84222
2 AAVQELSSSILAGEDPEER            S367        C3N-03884 18.93493
3 GVVPLAGTNGETTTQGLDGLSER        S132        C3N-03884 17.19216
4 TVPPAVTGITFLSGGQSEEEASINLNAINK S276        C3N-03884 16.82438
5 GILAADESTGSIAK                 S36         C3N-03884 23.08933
6 GILAADESTGSIAKR                S39         C3N-03884 22.97128

In [62]:
phospho_long_site <- phospho_long[
  ,
  .(
    gene_id = gene_id[1],
    protein_id = protein_id[1],
    peptide_id = site_id[1],
    modified_peptide_sequence = site_id[1],
    peptide_sequence = site_id[1],
    phosphosite = phosphosite[1],
    peptide_intensity = median(peptide_intensity, na.rm = TRUE)
  ),
  by = .(site_id, run_id)
]

phospho_long_site <- phospho_long_site[
  ,
  .(
    gene_id,
    protein_id,
    peptide_id,
    site_id,
    modified_peptide_sequence,
    peptide_sequence,
    phosphosite,
    run_id,
    peptide_intensity
  )
]

In [64]:
proteo <- fread("./data/cptac-pdac/proteomics_gene_level_MD_abundance_tumor.cct")

In [65]:
setnames(proteo, names(proteo)[1], "gene_id")

proteo[, gene_id := trimws(gene_id)]

sample_cols <- setdiff(names(proteo), "gene_id")

for (j in sample_cols) {
  set(
    proteo,
    i = which(!is.na(proteo[[j]]) & !is.finite(proteo[[j]])),
    j = j,
    value = NA_real_
  )
}

obs_n <- rowSums(!is.na(proteo[, ..sample_cols]))

summary(obs_n)

proteo <- proteo[obs_n > 0]

dim(proteo)

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
    0.0    70.0   135.0   105.5   140.0   140.0

[1] 11631   141

In [66]:
fasta_headers <- readLines("tools/references/library.fasta")
fasta_headers <- fasta_headers[grepl("^>", fasta_headers)]

protein_id <- sub("^>[^|]*\\|([^|]+)\\|.*", "\\1", fasta_headers)

gene_symbol <- ifelse(
  grepl(" GN=", fasta_headers),
  sub(".* GN=([^ ]+).*", "\\1", fasta_headers),
  NA_character_
)

map_dt <- data.table(
  gene_id = gene_symbol,
  protein_id = protein_id,
  fasta_header = fasta_headers
)

map_dt <- map_dt[!is.na(gene_id)]

map_dt[, is_sp := grepl("^>sp\\|", fasta_header)]
setorder(map_dt, gene_id, -is_sp)

map_dt <- map_dt[, .SD[1], by = gene_id]
map_dt <- map_dt[, .(gene_id, protein_id)]

In [67]:
proteo_annot <- merge(
  proteo,
  map_dt,
  by = "gene_id",
  all.x = TRUE
)

cat("genes in proteo:", nrow(proteo_annot), "\n")
cat("mapped genes:", sum(!is.na(proteo_annot$protein_id)), "\n")
cat("unmapped genes:", sum(is.na(proteo_annot$protein_id)), "\n")

head(proteo_annot[is.na(protein_id), gene_id], 50)

genes in proteo: 11631
mapped genes: 11480
unmapped genes: 151

 [1] "AAED1"           "ADGRE5"          "ADSS"            "ADSSL1"
 [5] "AES"             "ANKHD1-EIF4EBP3" "APOBEC3A_B"      "ATP5MF-PTCD1"
 [9] "ATP5S"           "BCL2L2-PABPN1"   "BUB1B-PAK6"      "C10orf88"
[13] "C11orf58"        "C12orf43"        "C12orf75"        "C15orf38-AP3S2"
[17] "C15orf48"        "C16orf45"        "C17orf49"        "C17orf97"
[21] "C19orf33"        "C19orf38"        "C19orf66"        "C19orf70"
[25] "C1orf116"        "C1orf123"        "C1orf35"         "C21orf2"
[29] "C2orf54"         "C3orf52"         "C3orf58"         "C4B_2"
[33] "C5orf15"         "C6orf106"        "C6orf203"        "C6orf222"
[37] "C6orf58"         "C7orf43"         "C7orf55-LUC7L2"  "C8orf59"
[41] "CENPS-CORT"      "COL4A3BP"        "COMMD3-BMI1"     "CORO7-PAM16"
[45] "CTGF"            "CXorf36"         "CYR61"           "DEFA1B"
[49] "DIRC2"           "F8A2"

In [68]:
proteo_annot <- proteo_annot[!is.na(protein_id)]

sample_cols <- setdiff(names(proteo_annot), c("gene_id", "protein_id"))

proteo_long <- melt(
  proteo_annot,
  id.vars = c("gene_id", "protein_id"),
  measure.vars = sample_cols,
  variable.name = "run_id",
  value.name = "peptide_intensity",
  variable.factor = FALSE,
  na.rm = FALSE
)

proteo_long[, run_id := as.character(run_id)]

proteo_long[, peptide_id := protein_id]
proteo_long[, modified_peptide_sequence := protein_id]
proteo_long[, peptide_sequence := protein_id]
proteo_long[, phosphosite := "PA"]
proteo_long[, site_id := paste(gene_id, protein_id, phosphosite, sep = ":")]

proteo_long <- proteo_long[
  ,
  .(
    gene_id,
    protein_id,
    peptide_id,
    site_id,
    modified_peptide_sequence,
    peptide_sequence,
    phosphosite,
    run_id,
    peptide_intensity
  )
]

dim(proteo_long)
head(proteo_long)

[1] 1607200       9

  gene_id protein_id peptide_id site_id          modified_peptide_sequence
1 A1BG    P04217     P04217     A1BG:P04217:PA   P04217
2 A1CF    Q9NQ94     Q9NQ94     A1CF:Q9NQ94:PA   Q9NQ94
3 A2M     P01023     P01023     A2M:P01023:PA    P01023
4 A2ML1   A8K2U0     A8K2U0     A2ML1:A8K2U0:PA  A8K2U0
5 A4GALT  Q9NPC4     Q9NPC4     A4GALT:Q9NPC4:PA Q9NPC4
6 A4GNT   Q9UNA3     Q9UNA3     A4GNT:Q9UNA3:PA  Q9UNA3
  peptide_sequence phosphosite run_id    peptide_intensity
1 P04217           PA          C3L-03394 28.67421
2 Q9NQ94           PA          C3L-03394 24.02035
3 P01023           PA          C3L-03394 29.77424
4 A8K2U0           PA          C3L-03394       NA
5 Q9NPC4           PA          C3L-03394       NA
6 Q9UNA3           PA          C3L-03394       NA

In [69]:
dir.create("./data/cptac-pdac/processed")

Warning message in dir.create("./data/cptac-pdac/processed"):
“'./data/cptac-pdac/processed' already exists”

In [70]:
saveRDS(phospho_long_site, "./data/cptac-pdac/processed/CPTAC_PDAC_phospho.rds")
saveRDS(proteo_long, "./data/cptac-pdac/processed/CPTAC_PDAC_proteo.rds")